<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PermissionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('permissions')->insert([
//            [
//                'id' => 1,
//                'name' => 'users-list',
//                'libelle' => 'Liste',
//                'guard_name' => 'web',
//                'feature_id' => 5,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'id' => 2,
//                'name' => 'users-create',
//                'libelle' => 'Nouveau',
//                'guard_name' => 'web',
//                'feature_id' => 5,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'id' => 3,
//                'name' => 'users-edit',
//                'libelle' => 'Modifier',
//                'guard_name' => 'web',
//                'feature_id' => 5,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'id' => 4,
//                'name' => 'users-statut',
//                'libelle' => 'Supprimer',
//                'guard_name' => 'web',
//                'feature_id' => 5,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'id' => 5,
//                'name' => 'users-profile',
//                'libelle' => 'Profil',
//                'guard_name' => 'web',
//                'feature_id' => 5,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//
//            //role
//            [
//                'id' => 6,
//                'name' => 'roles-list',
//                'libelle' => 'Liste',
//                'guard_name' => 'web',
//                'feature_id' => 4,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'id' => 7,
//                'name' => 'roles-create',
//                'libelle' => 'Nouveau',
//                'guard_name' => 'web',
//                'feature_id' => 4,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'id' => 8,
//                'name' => 'roles-edit',
//                'libelle' => 'Modifier',
//                'guard_name' => 'web',
//                'feature_id' => 4,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'id' => 9,
//                'name' => 'roles-statut',
//                'libelle' => 'Supprimer',
//                'guard_name' => 'web',
//                'feature_id' => 4,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//
//            //permission
//
//            [
//                'id' => 10,
//                'name' => 'permission-list',
//                'libelle' => 'Liste',
//                'guard_name' => 'web',
//                'feature_id' => 3,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'id' => 11,
//                'name' => 'permission-create',
//                'libelle' => 'Nouveau',
//                'guard_name' => 'web',
//                'feature_id' => 3,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'id' => 12,
//                'name' => 'permission-edit',
//                'libelle' => 'Modifier',
//                'guard_name' => 'web',
//                'feature_id' => 3,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'id' => 13,
//                'name' => 'permission-statut',
//                'libelle' => 'Supprimer',
//                'guard_name' => 'web',
//                'feature_id' => 3,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//
//            //MODULE
//            [
//                'id' => 14,
//                'name' => 'module-list',
//                'libelle' => 'Liste',
//                'guard_name' => 'web',
//                'feature_id' =>1,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'id' => 15,
//                'name' => 'module-create',
//                'libelle' => 'Nouveau',
//                'guard_name' => 'web',
//                'feature_id' => 1,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'id' => 16,
//                'name' => 'module-edit',
//                'libelle' => 'Modifier',
//                'guard_name' => 'web',
//                'feature_id' => 1,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'id' => 17,
//                'name' => 'module-statut',
//                'libelle' => 'Supprimer',
//                'guard_name' => 'web',
//                'feature_id' => 1,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//
//            //FONCTIONNALITE 5
//            [
//                'id' => 18,
//                'name' => 'feature-list',
//                'libelle' => 'Liste',
//                'guard_name' => 'web',
//                'feature_id' => 2,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'id' => 19,
//                'name' => 'feature-create',
//                'libelle' => 'Nouveau',
//                'guard_name' => 'web',
//                'feature_id' => 2,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'id' => 20,
//                'name' => 'feature-edit',
//                'libelle' => 'Modifier',
//                'guard_name' => 'web',
//                'feature_id' => 2,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'id' => 21,
//                'name' => 'feature-statut',
//                'libelle' => 'Supprimer',
//                'guard_name' => 'web',
//                'feature_id' => 2,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            //PAYS
//            [
//                'id' => 22,
//                'name' => 'pays-list',
//                'libelle' => 'Liste',
//                'guard_name' => 'web',
//                'feature_id' => 6,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'id' => 23,
//                'name' => 'pays-create',
//                'libelle' => 'Nouveau',
//                'guard_name' => 'web',
//                'feature_id' => 6,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'id' => 24,
//                'name' => 'pays-edit',
//                'libelle' => 'Modifier',
//                'guard_name' => 'web',
//                'feature_id' => 6,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'id' => 25,
//                'name' => 'pays-statut',
//                'libelle' => 'Supprimer',
//                'guard_name' => 'web',
//                'feature_id' => 6,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            //DEVISE
//            [
//                'id' => 26,
//                'name' => 'devise-list',
//                'libelle' => 'Liste',
//                'guard_name' => 'web',
//                'feature_id' => 7,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'id' => 27,
//                'name' => 'devise-create',
//                'libelle' => 'Nouveau',
//                'guard_name' => 'web',
//                'feature_id' => 7,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'id' => 28,
//                'name' => 'devise-edit',
//                'libelle' => 'Modifier',
//                'guard_name' => 'web',
//                'feature_id' => 7,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'id' => 29,
//                'name' => 'devise-statut',
//                'libelle' => 'Supprimer',
//                'guard_name' => 'web',
//                'feature_id' => 7,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            //PAYS DEVISE
//            [
//                'id' => 30,
//                'name' => 'paysdevise-list',
//                'libelle' => 'Liste',
//                'guard_name' => 'web',
//                'feature_id' => 8,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'id' => 31,
//                'name' => 'paysdevise-create',
//                'libelle' => 'Nouveau',
//                'guard_name' => 'web',
//                'feature_id' => 8,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'id' => 32,
//                'name' => 'paysdevise-edit',
//                'libelle' => 'Modifier',
//                'guard_name' => 'web',
//                'feature_id' => 8,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'id' => 33,
//                'name' => 'paysdevise-statut',
//                'libelle' => 'Supprimer',
//                'guard_name' => 'web',
//                'feature_id' => 8,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            //ZONE
//            [
//                'id' => 34,
//                'name' => 'zone-list',
//                'libelle' => 'Liste',
//                'guard_name' => 'web',
//                'feature_id' => 9,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'id' => 35,
//                'name' => 'zone-create',
//                'libelle' => 'Nouveau',
//                'guard_name' => 'web',
//                'feature_id' => 9,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'id' => 36,
//                'name' => 'zone-edit',
//                'libelle' => 'Modifier',
//                'guard_name' => 'web',
//                'feature_id' => 9,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'id' => 37,
//                'name' => 'zone-statut',
//                'libelle' => 'Supprimer',
//                'guard_name' => 'web',
//                'feature_id' => 9,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            //FOURNISSEUR PAIEMENT
//            [
//                'id' => 38,
//                'name' => 'fournisseurpaiement-list',
//                'libelle' => 'Liste',
//                'guard_name' => 'web',
//                'feature_id' => 10,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'id' => 39,
//                'name' => 'fournisseurpaiement-create',
//                'libelle' => 'Nouveau',
//                'guard_name' => 'web',
//                'feature_id' => 10,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'id' => 40,
//                'name' => 'fournisseurpaiement-edit',
//                'libelle' => 'Modifier',
//                'guard_name' => 'web',
//                'feature_id' => 10,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'id' => 41,
//                'name' => 'fournisseurpaiement-statut',
//                'libelle' => 'Supprimer',
//                'guard_name' => 'web',
//                'feature_id' => 10,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//
//            //SESSION
//            [
//                'id' => 42,
//                'name' => 'session-list',
//                'libelle' => 'Liste',
//                'guard_name' => 'web',
//                'feature_id' => 11,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'id' => 43,
//                'name' => 'session-delete',
//                'libelle' => 'Supprimer',
//                'guard_name' => 'web',
//                'feature_id' => 11,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            //Marchand
//            [
//                'id' => 44,
//                'name' => 'marchand-list',
//                'libelle' => 'Liste',
//                'guard_name' => 'web',
//                'feature_id' => 12,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'id' => 45,
//                'name' => 'marchand-create',
//                'libelle' => 'Nouveau',
//                'guard_name' => 'web',
//                'feature_id' => 12,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'id' => 46,
//                'name' => 'marchand-edit',
//                'libelle' => 'Modifier',
//                'guard_name' => 'web',
//                'feature_id' => 12,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'id' => 47,
//                'name' => 'marchand-statut',
//                'libelle' => 'Supprimer',
//                'guard_name' => 'web',
//                'feature_id' => 12,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ]
//            ,
//            [
//                'id' => 48,
//                'name' => 'marchand-validate',
//                'libelle' => 'Valider',
//                'guard_name' => 'web',
//                'feature_id' => 12,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            //Point de vente
//            [
//                'id' => 49,
//                'name' => 'pointvente-list',
//                'libelle' => 'Liste',
//                'guard_name' => 'web',
//                'feature_id' => 13,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'id' => 50,
//                'name' => 'pointvente-create',
//                'libelle' => 'Nouveau',
//                'guard_name' => 'web',
//                'feature_id' => 13,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'id' => 51,
//                'name' => 'pointvente-edit',
//                'libelle' => 'Modifier',
//                'guard_name' => 'web',
//                'feature_id' => 13,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'id' => 52,
//                'name' => 'pointvente-statut',
//                'libelle' => 'Supprimer',
//                'guard_name' => 'web',
//                'feature_id' => 13,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ]
//            ,
//            [
//                'id' => 53,
//                'name' => 'pointvente-validate',
//                'libelle' => 'Valider',
//                'guard_name' => 'web',
//                'feature_id' => 13,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//             //Employés
//            [
//                'id' => 54,
//                'name' => 'employe-list',
//                'libelle' => 'Liste',
//                'guard_name' => 'web',
//                'feature_id' => 14,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'id' => 55,
//                'name' => 'employe-create',
//                'libelle' => 'Nouveau',
//                'guard_name' => 'web',
//                'feature_id' => 14,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'id' => 56,
//                'name' => 'employe-edit',
//                'libelle' => 'Modifier',
//                'guard_name' => 'web',
//                'feature_id' => 14,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'id' => 57,
//                'name' => 'employe-statut',
//                'libelle' => 'Supprimer',
//                'guard_name' => 'web',
//                'feature_id' => 14,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ]
//            ,
//            [
//                'id' => 58,
//                'name' => 'employe-validate',
//                'libelle' => 'Valider',
//                'guard_name' => 'web',
//                'feature_id' => 14,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//              //Articles
//             [
//                 'id' => 59,
//                 'name' => 'article-list',
//                 'libelle' => 'Liste',
//                 'guard_name' => 'web',
//                 'feature_id' => 15,
//                 'created_at' => now(),
//                 'updated_at' => now(),
//             ],
//             [
//                 'id' => 60,
//                 'name' => 'article-create',
//                 'libelle' => 'Nouveau',
//                 'guard_name' => 'web',
//                 'feature_id' => 15,
//                 'created_at' => now(),
//                 'updated_at' => now(),
//             ],
//             [
//                 'id' => 61,
//                 'name' => 'article-edit',
//                 'libelle' => 'Modifier',
//                 'guard_name' => 'web',
//                 'feature_id' => 15,
//                 'created_at' => now(),
//                 'updated_at' => now(),
//             ],
//             [
//                 'id' => 62,
//                 'name' => 'article-statut',
//                 'libelle' => 'Supprimer',
//                 'guard_name' => 'web',
//                 'feature_id' => 15,
//                 'created_at' => now(),
//                 'updated_at' => now(),
//             ],
//
//            // Admin (Personnel) - feature_id = 16
//             [
//                 'id' => 63,
//                 'name' => 'admin-list',
//                 'libelle' => 'Liste',
//                 'guard_name' => 'web',
//                 'feature_id' => 16,
//                 'created_at' => now(),
//                 'updated_at' => now(),
//             ],
//             [
//                 'id' => 64,
//                 'name' => 'admin-create',
//                 'libelle' => 'Nouveau',
//                 'guard_name' => 'web',
//                 'feature_id' => 16,
//                 'created_at' => now(),
//                 'updated_at' => now(),
//             ],
//             [
//                 'id' => 65,
//                 'name' => 'admin-edit',
//                 'libelle' => 'Modifier',
//                 'guard_name' => 'web',
//                 'feature_id' => 16,
//                 'created_at' => now(),
//                 'updated_at' => now(),
//             ],
//             [
//                 'id' => 66,
//                 'name' => 'admin-statut',
//                 'libelle' => 'Supprimer',
//                 'guard_name' => 'web',
//                 'feature_id' => 16,
//                 'created_at' => now(),
//                 'updated_at' => now(),
//             ],
//             [
//                 'id' => 67,
//                 'name' => 'admin-validate',
//                 'libelle' => 'Valider',
//                 'guard_name' => 'web',
//                 'feature_id' => 16,
//                 'created_at' => now(),
//                 'updated_at' => now(),
//             ],
//
//             // Agent - feature_id = 17
//             [
//                 'id' => 68,
//                 'name' => 'agent-list',
//                 'libelle' => 'Liste',
//                 'guard_name' => 'web',
//                 'feature_id' => 17,
//                 'created_at' => now(),
//                 'updated_at' => now(),
//             ],
//             [
//                 'id' => 69,
//                 'name' => 'agent-create',
//                 'libelle' => 'Nouveau',
//                 'guard_name' => 'web',
//                 'feature_id' => 17,
//                 'created_at' => now(),
//                 'updated_at' => now(),
//             ],
//             [
//                 'id' => 70,
//                 'name' => 'agent-edit',
//                 'libelle' => 'Modifier',
//                 'guard_name' => 'web',
//                 'feature_id' => 17,
//                 'created_at' => now(),
//                 'updated_at' => now(),
//             ],
//             [
//                 'id' => 71,
//                 'name' => 'agent-statut',
//                 'libelle' => 'Supprimer',
//                 'guard_name' => 'web',
//                 'feature_id' => 17,
//                 'created_at' => now(),
//                 'updated_at' => now(),
//             ],
//             [
//                 'id' => 72,
//                 'name' => 'agent-validate',
//                 'libelle' => 'Valider',
//                 'guard_name' => 'web',
//                 'feature_id' => 17,
//                 'created_at' => now(),
//                 'updated_at' => now(),
//             ],
//
//            // Service Client - feature_id = 18
//             [
//                 'id' => 73,
//                 'name' => 'service_client-list',
//                 'libelle' => 'Liste',
//                 'guard_name' => 'web',
//                 'feature_id' => 18,
//                 'created_at' => now(),
//                 'updated_at' => now(),
//             ],
//             [
//                 'id' => 74,
//                 'name' => 'service_client-create',
//                 'libelle' => 'Nouveau',
//                 'guard_name' => 'web',
//                 'feature_id' => 18,
//                 'created_at' => now(),
//                 'updated_at' => now(),
//             ],
//             [
//                 'id' => 75,
//                 'name' => 'service_client-edit',
//                 'libelle' => 'Modifier',
//                 'guard_name' => 'web',
//                 'feature_id' => 18,
//                 'created_at' => now(),
//                 'updated_at' => now(),
//             ],
//             [
//                 'id' => 76,
//                 'name' => 'service_client-statut',
//                 'libelle' => 'Supprimer',
//                 'guard_name' => 'web',
//                 'feature_id' => 18,
//                 'created_at' => now(),
//                 'updated_at' => now(),
//             ],
//             [
//                 'id' => 77,
//                 'name' => 'service_client-validate',
//                 'libelle' => 'Valider',
//                 'guard_name' => 'web',
//                 'feature_id' => 18,
//                 'created_at' => now(),
//                 'updated_at' => now(),
//             ],
//
//            // Service Validateur - feature_id = 19
//             [
//                 'id' => 78,
//                 'name' => 'service_validateur-list',
//                 'libelle' => 'Liste',
//                 'guard_name' => 'web',
//                 'feature_id' => 19,
//                 'created_at' => now(),
//                 'updated_at' => now(),
//             ],
//             [
//                 'id' => 79,
//                 'name' => 'service_validateur-create',
//                 'libelle' => 'Nouveau',
//                 'guard_name' => 'web',
//                 'feature_id' => 19,
//                 'created_at' => now(),
//                 'updated_at' => now(),
//             ],
//             [
//                 'id' => 80,
//                 'name' => 'service_validateur-edit',
//                 'libelle' => 'Modifier',
//                 'guard_name' => 'web',
//                 'feature_id' => 19,
//                 'created_at' => now(),
//                 'updated_at' => now(),
//             ],
//             [
//                 'id' => 81,
//                 'name' => 'service_validateur-statut',
//                 'libelle' => 'Supprimer',
//                 'guard_name' => 'web',
//                 'feature_id' => 19,
//                 'created_at' => now(),
//                 'updated_at' => now(),
//             ],
//             [
//                 'id' => 82,
//                 'name' => 'service_validateur-validate',
//                 'libelle' => 'Valider',
//                 'guard_name' => 'web',
//                 'feature_id' => 19,
//                 'created_at' => now(),
//                 'updated_at' => now(),
//             ],
//
//            //Client
//              [
//                'id' => 83,
//                'name' => 'client-list',
//                'libelle' => 'Liste',
//                'guard_name' => 'web',
//                'feature_id' => 20,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'id' => 84,
//                'name' => 'client-create',
//                'libelle' => 'Nouveau',
//                'guard_name' => 'web',
//                'feature_id' => 20,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'id' => 85,
//                'name' => 'client-edit',
//                'libelle' => 'Modifier',
//                'guard_name' => 'web',
//                'feature_id' => 20,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'id' => 86,
//                'name' => 'client-statut',
//                'libelle' => 'Supprimer',
//                'guard_name' => 'web',
//                'feature_id' => 20,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'id' => 87,
//                'name' => 'client-validate',
//                'libelle' => 'Valider',
//                'guard_name' => 'web',
//                'feature_id' => 20,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//
//            // Caisse - feature_id = 21
//           [
//               'id' => 88,
//               'name' => 'caisse-list',
//               'libelle' => 'Liste',
//               'guard_name' => 'web',
//               'feature_id' => 21,
//               'created_at' => now(),
//               'updated_at' => now(),
//           ],
//           [
//               'id' => 89,
//               'name' => 'caisse-create',
//               'libelle' => 'Nouveau',
//               'guard_name' => 'web',
//               'feature_id' => 21,
//               'created_at' => now(),
//               'updated_at' => now(),
//           ],
//           [
//               'id' => 90,
//               'name' => 'caisse-edit',
//               'libelle' => 'Modifier',
//               'guard_name' => 'web',
//               'feature_id' => 21,
//               'created_at' => now(),
//               'updated_at' => now(),
//           ],
//           [
//               'id' => 91,
//               'name' => 'caisse-statut',
//               'libelle' => 'Supprimer',
//               'guard_name' => 'web',
//               'feature_id' => 21,
//               'created_at' => now(),
//               'updated_at' => now(),
//           ],
//
//            // Terminal - feature_id = 22
//           [
//               'id' => 92,
//               'name' => 'terminal-list',
//               'libelle' => 'Liste',
//               'guard_name' => 'web',
//               'feature_id' => 22,
//               'created_at' => now(),
//               'updated_at' => now(),
//           ],
//           [
//               'id' => 93,
//               'name' => 'terminal-create',
//               'libelle' => 'Nouveau',
//               'guard_name' => 'web',
//               'feature_id' => 22,
//               'created_at' => now(),
//               'updated_at' => now(),
//           ],
//           [
//               'id' => 94,
//               'name' => 'terminal-edit',
//               'libelle' => 'Modifier',
//               'guard_name' => 'web',
//               'feature_id' => 22,
//               'created_at' => now(),
//               'updated_at' => now(),
//           ],
//           [
//               'id' => 95,
//               'name' => 'terminal-statut',
//               'libelle' => 'Supprimer',
//               'guard_name' => 'web',
//               'feature_id' => 22,
//               'created_at' => now(),
//               'updated_at' => now(),
//           ],
//            [
//               'id' => 96,
//               'name' => 'terminal-validate',
//               'libelle' => 'Valider',
//               'guard_name' => 'web',
//               'feature_id' => 22,
//               'created_at' => now(),
//               'updated_at' => now(),
//           ],
//       // Session Caisse Manager - feature_id = 23
//           [
//               'id' => 97,
//               'name' => 'session-caisse-manager-list',
//               'libelle' => 'Liste',
//               'guard_name' => 'web',
//               'feature_id' => 23,
//               'created_at' => now(),
//               'updated_at' => now(),
//           ],
//           [
//               'id' => 98,
//               'name' => 'session-caisse-manager-create',
//               'libelle' => 'Nouveau',
//               'guard_name' => 'web',
//               'feature_id' => 23,
//               'created_at' => now(),
//               'updated_at' => now(),
//           ],
//           [
//               'id' => 105,
//               'name' => 'session-caisse-manager-fermerture',
//               'libelle' => 'Fermeture',
//               'guard_name' => 'web',
//               'feature_id' => 23,
//               'created_at' => now(),
//               'updated_at' => now(),
//           ],
//            // Session Caisse Caissier - feature_id = 24
//           [
//               'id' => 99,
//               'name' => 'session-caisse-caissier-list',
//               'libelle' => 'Liste',
//               'guard_name' => 'web',
//               'feature_id' => 24,
//               'created_at' => now(),
//               'updated_at' => now(),
//           ],
//           [
//               'id' => 100,
//               'name' => 'session-caisse-caissier-ouverture',
//               'libelle' => 'Ouverture',
//               'guard_name' => 'web',
//               'feature_id' => 24,
//               'created_at' => now(),
//               'updated_at' => now(),
//           ],
//            [
//               'id' => 101,
//               'name' => 'session-caisse-caissier-fermerture',
//               'libelle' => 'Fermeture',
//               'guard_name' => 'web',
//               'feature_id' => 24,
//               'created_at' => now(),
//               'updated_at' => now(),
//           ],
//            [
//               'id' => 102,
//               'name' => 'session-caisse-caissier-remboursement',
//               'libelle' => 'Remboursement',
//               'guard_name' => 'web',
//               'feature_id' => 24,
//               'created_at' => now(),
//               'updated_at' => now(),
//           ],
//                 //ERRORLOG
//                 [
//                     'id' => 103,
//                     'name' => 'errorlog-list',
//                     'libelle' => 'Liste',
//                     'guard_name' => 'web',
//                     'feature_id' => 25,
//                     'created_at' => now(),
//                     'updated_at' => now(),
//                 ],
//                 [
//                     'id' => 104,
//                     'name' => 'errorlog-delete',
//                     'libelle' => 'Supprimer',
//                     'guard_name' => 'web',
//                     'feature_id' => 25,
//                     'created_at' => now(),
//                     'updated_at' => now(),
//                 ],
//                       // Vente POS - feature_id = 26
//           [
//               'id' => 106,
//               'name' => 'ventepos-list',
//               'libelle' => 'Liste',
//               'guard_name' => 'web',
//               'feature_id' => 26,
//               'created_at' => now(),
//               'updated_at' => now(),
//           ],
//           [
//               'id' => 107,
//               'name' => 'ventepos-create',
//               'libelle' => 'Nouveau',
//               'guard_name' => 'web',
//               'feature_id' => 26,
//               'created_at' => now(),
//               'updated_at' => now(),
//           ],
//           [
//               'id' => 108,
//               'name' => 'ventepos-edit',
//               'libelle' => 'Modifier',
//               'guard_name' => 'web',
//               'feature_id' => 26,
//               'created_at' => now(),
//               'updated_at' => now(),
//           ],
//           [
//               'id' => 109,
//               'name' => 'ventepos-validate',
//               'libelle' => 'Valider',
//               'guard_name' => 'web',
//               'feature_id' => 26,
//               'created_at' => now(),
//               'updated_at' => now(),
//           ],
//            [
//               'id' => 110,
//               'name' => 'ventepos-cancel',
//               'libelle' => 'Annuler',
//               'guard_name' => 'web',
//               'feature_id' => 26,
//               'created_at' => now(),
//               'updated_at' => now(),
//           ],
//            [
//               'id' => 111,
//               'name' => 'ventepos-refund',
//               'libelle' => 'Remboursement',
//               'guard_name' => 'web',
//               'feature_id' => 26,
//               'created_at' => now(),
//               'updated_at' => now(),
//           ],
//            [
//               'id' => 112,
//               'name' => 'ventepos-refund-line',
//               'libelle' => 'Remboursement par ligne',
//               'guard_name' => 'web',
//               'feature_id' => 26,
//               'created_at' => now(),
//               'updated_at' => now(),
//           ],
//            [
//               'id' => 113,
//               'name' => 'ventepos-refund-quantite',
//               'libelle' => 'Remboursement par quantité',
//               'guard_name' => 'web',
//               'feature_id' => 26,
//               'created_at' => now(),
//               'updated_at' => now(),
//           ],
//            [
//               'id' => 114,
//               'name' => 'ventepos-refund-mixte',
//               'libelle' => 'Remboursement mixte',
//               'guard_name' => 'web',
//               'feature_id' => 26,
//               'created_at' => now(),
//               'updated_at' => now(),
//           ],
//            [
//               'id' => 115,
//               'name' => 'ventepos-refund-mixte-quantite',
//               'libelle' => 'Remboursement mixte & quantité',
//               'guard_name' => 'web',
//               'feature_id' => 26,
//               'created_at' => now(),
//               'updated_at' => now(),
//           ],
//          // Stock movement - feature_id = 27
//           [
//               'id' => 116,
//               'name' => 'mouvement-stock-list',
//               'libelle' => 'Liste',
//               'guard_name' => 'web',
//               'feature_id' => 27,
//               'created_at' => now(),
//               'updated_at' => now(),
//           ],
//           [
//               'id' => 117,
//               'name' => 'mouvement-stock-create',
//               'libelle' => 'Nouveau',
//               'guard_name' => 'web',
//               'feature_id' => 27,
//               'created_at' => now(),
//               'updated_at' => now(),
//           ],
//            // Transfert stock - feature_id = 28
//           [
//               'id' => 118,
//               'name' => 'transfert-stock-list',
//               'libelle' => 'Liste',
//               'guard_name' => 'web',
//               'feature_id' => 28,
//               'created_at' => now(),
//               'updated_at' => now(),
//           ],
//           [
//               'id' => 119,
//               'name' => 'transfert-stock-create',
//               'libelle' => 'Nouveau',
//               'guard_name' => 'web',
//               'feature_id' => 28,
//               'created_at' => now(),
//               'updated_at' => now(),
//           ],
//            [
//               'id' => 120,
//               'name' => 'transfert-stock-edit',
//               'libelle' => 'Modifier',
//               'guard_name' => 'web',
//               'feature_id' => 28,
//               'created_at' => now(),
//               'updated_at' => now(),
//           ],
//            [
//               'id' => 121,
//               'name' => 'transfert-stock-statut',
//               'libelle' => 'Supprimer',
//               'guard_name' => 'web',
//               'feature_id' => 28,
//               'created_at' => now(),
//               'updated_at' => now(),
//           ],
//            [
//               'id' => 122,
//               'name' => 'transfert-stock-validate',
//               'libelle' => 'Valider',
//               'guard_name' => 'web',
//               'feature_id' => 28,
//               'created_at' => now(),
//               'updated_at' => now(),
//           ],
//            // Inventaire - feature_id = 29
//            [
//                'id' => 123,
//                'name' => 'inventaire-list',
//                'libelle' => 'Liste',
//                'guard_name' => 'web',
//                'feature_id' => 29,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'id' => 124,
//                'name' => 'inventaire-create',
//                'libelle' => 'Nouveau',
//                'guard_name' => 'web',
//                'feature_id' => 29,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'id' => 125,
//                'name' => 'inventaire-edit',
//                'libelle' => 'Modifier',
//                'guard_name' => 'web',
//                'feature_id' => 29,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'id' => 126,
//                'name' => 'inventaire-statut',
//                'libelle' => 'Supprimer',
//                'guard_name' => 'web',
//                'feature_id' => 29,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'id' => 127,
//                'name' => 'inventaire-validate',
//                'libelle' => 'Valider',
//                'guard_name' => 'web',
//                'feature_id' => 29,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            // Banque - feature_id = 30
//            [
//                'id' => 128,
//                'name' => 'banque-list',
//                'libelle' => 'Liste',
//                'guard_name' => 'web',
//                'feature_id' => 30,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'id' => 129,
//                'name' => 'banque-create',
//                'libelle' => 'Nouveau',
//                'guard_name' => 'web',
//                'feature_id' => 30,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'id' => 130,
//                'name' => 'banque-edit',
//                'libelle' => 'Modifier',
//                'guard_name' => 'web',
//                'feature_id' => 30,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'id' => 131,
//                'name' => 'banque-statut',
//                'libelle' => 'Supprimer',
//                'guard_name' => 'web',
//                'feature_id' => 30,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            // Compte Bancaire Marchand - feature_id = 31
//            [
//                'id' => 132,
//                'name' => 'compte-bancaire-marchand-list',
//                'libelle' => 'Liste',
//                'guard_name' => 'web',
//                'feature_id' => 31,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'id' => 133,
//                'name' => 'compte-bancaire-marchand-create',
//                'libelle' => 'Nouveau',
//                'guard_name' => 'web',
//                'feature_id' => 31,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'id' => 134,
//                'name' => 'compte-bancaire-marchand-edit',
//                'libelle' => 'Modifier',
//                'guard_name' => 'web',
//                'feature_id' => 31,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'id' => 135,
//                'name' => 'compte-bancaire-marchand-statut',
//                'libelle' => 'Supprimer',
//                'guard_name' => 'web',
//                'feature_id' => 31,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            // Wallet - feature_id = 32
//            [
//                'id' => 136,
//                'name' => 'wallet-list',
//                'libelle' => 'Liste',
//                'guard_name' => 'web',
//                'feature_id' => 32,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'id' => 137,
//                'name' => 'wallet-edit',
//                'libelle' => 'Modifier',
//                'guard_name' => 'web',
//                'feature_id' => 32,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'id' => 138,
//                'name' => 'wallet-statut',
//                'libelle' => 'Supprimer',
//                'guard_name' => 'web',
//                'feature_id' => 32,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],
//            [
//                'id' => 139,
//                'name' => 'wallet-show-by-owner',
//                'libelle' => 'Voir wallet du propriétaire',
//                'guard_name' => 'web',
//                'feature_id' => 32,
//                'created_at' => now(),
//                'updated_at' => now(),
//            ],

        ]);
    }
}
