<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TFeatureTestSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('feature')->insert([
            [
                'id' => 1,
                'libelle' => 'Module',
                'libelle_en' => 'Module',
                'module_id' => 1,
                'menu_url' => 'module',
                'icone' => 'fas fa-wrench',
                'ordre' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],[
                'id' => 2,
                'libelle' => 'Fonctionnalité',
                'libelle_en' => 'Functionality',
                'module_id' => 1,
                'menu_url' => 'feature',
                'icone' => 'fas fa-wrench',
                'ordre' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 3,
                'libelle' => 'Permission',
                'libelle_en' => 'Permission',
                'module_id' => 1,
                'menu_url' => 'permission',
                'icone' => "fas fa-wrench",
                'ordre' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'libelle' => 'Gestion des profils',
                'libelle_en' => 'Profiles',
                'module_id' => 1,
                'menu_url' => 'roles',
                'icone' => 'fas fa-users-cog',
                'ordre' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'libelle' => 'Gestion des utilisateurs',
                'libelle_en' => 'Users Management',
                'module_id' => 1,
                'menu_url' => 'users',
                'icone' => 'fas fa-user-tie',
                'ordre' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'libelle' => 'Pays',
                'libelle_en' => 'Country',
                'module_id' => 2,
                'menu_url' => 'pays',
                'icone' => 'fas fa-globe',
                'ordre' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'libelle' => 'Devise',
                'libelle_en' => 'Currency',
                'module_id' => 2,
                'menu_url' => 'devise',
                'icone' => 'fas fa-money-bill',
                'ordre' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // [
            //     'id' => 8,
            //     'libelle' => "Devises d'un pays",
            //     'libelle_en' => 'Currencies of a country',
            //     'module_id' => 2,
            //     'menu_url' => 'paysdevise',
            //     'icone' => 'fas fa-wrench',
            //     'ordre' => 6,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ], // TODO: Create PaysDeviseController and routes
            [
                'id' => 9,
                'libelle' => "Zones d'un pays",
                'libelle_en' => 'Zones of a country',
                'module_id' => 2,
                'menu_url' => 'zone',
                'icone' => 'fas fa-map',
                'ordre' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'libelle' => 'Fournisseurs de paiement',
                'libelle_en' => 'Payment providers',
                'module_id' => 2,
                'menu_url' => 'fournisseurpaiement',
                'icone' => 'fas fa-wrench',
                'ordre' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
             [
                'id' => 11,
                'libelle' => 'Session',
                'libelle_en' => 'Session',
                'module_id' => 1,
                'menu_url' => 'session',
                'icone' => 'fas fa-wrench',
                'ordre' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ]
            ,
             [
                'id' => 12,
                'libelle' => 'Marchands',
                'libelle_en' => 'Merchants',
                'module_id' => 3,
                'menu_url' => 'marchand',
                'icone' => 'fas fa-store',
                'ordre' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ]
            ,
             [
                'id' => 13,
                'libelle' => 'Points de vente',
                'libelle_en' => 'Sales points',
                'module_id' => 3,
                'menu_url' => 'pointvente',
                'icone' => 'fas fa-map-marker-alt',
                'ordre' => 2,
                'created_at' => now(),
                'updated_at' => now(),

            ]
            ,
             [
                'id' => 14,
                'libelle' => 'Employés',
                'libelle_en' => 'Employees',
                'module_id' => 3,
                'menu_url' => 'employe',
                'icone' => 'fas fa-users',
                'ordre' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
              [
                 'id' => 15,
                 'libelle' => 'Articles',
                 'libelle_en' => 'Articles',
                 'module_id' => 7,
                 'menu_url' => 'article',
                 'icone' => 'fas fa-boxes',
                 'ordre' => 1,
                 'created_at' => now(),
                 'updated_at' => now(),
             ],
            // Module Personnel (module_id = 4)
             [
                 'id' => 16,
                 'libelle' => 'Administrateurs',
                 'libelle_en' => 'Administrators',
                 'module_id' => 4,
                 'menu_url' => 'admin',
                 'icone' => 'fas fa-user-shield',
                 'ordre' => 1,
                 'created_at' => now(),
                 'updated_at' => now(),
             ],
             [
                 'id' => 17,
                 'libelle' => 'Agents',
                 'libelle_en' => 'Agents',
                 'module_id' => 4,
                 'menu_url' => 'agent',
                 'icone' => 'fas fa-user-tie',
                 'ordre' => 2,
                 'created_at' => now(),
                 'updated_at' => now(),
             ],
             [
                 'id' => 18,
                 'libelle' => 'Service Client',
                 'libelle_en' => 'Customer Service',
                 'module_id' => 4,
                 'menu_url' => 'service_client',
                 'icone' => 'fas fa-headset',
                 'ordre' => 3,
                 'created_at' => now(),
                 'updated_at' => now(),
             ],
             [
                 'id' => 19,
                 'libelle' => 'Service Validateur',
                 'libelle_en' => 'Validator Service',
                 'module_id' => 4,
                 'menu_url' => 'service_validateur',
                 'icone' => 'fas fa-user-check',
                 'ordre' => 4,
                 'created_at' => now(),
                 'updated_at' => now(),
             ],
               [
                'id' => 20,
                'libelle' => 'Client',
                'libelle_en' => 'Client',
                'module_id' => 5,
                'menu_url' => 'client',
                'icone' => 'fas fa-user-check',
                'ordre' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
           [
               'id' => 21,
               'libelle' => 'Caisses',
               'libelle_en' => 'Cash Registers',
               'module_id' => 3,
               'menu_url' => 'caisse',
               'icone' => 'fas fa-cash-register',
               'ordre' => 5,
               'created_at' => now(),
               'updated_at' => now(),
           ],
           [
               'id' => 22,
               'libelle' => 'Terminaux',
               'libelle_en' => 'Terminals',
               'module_id' => 3,
               'menu_url' => 'terminal',
               'icone' => 'fas fa-tablet-alt',
               'ordre' => 6,
               'created_at' => now(),
               'updated_at' => now(),
           ],
        [
               'id' => 23,
               'libelle' => 'Session Caisse Manager',
               'libelle_en' => 'Cashier Manager session',
               'module_id' => 6,
               'menu_url' => 'session-caisse-manager',
               'icone' => 'fas fa-cash-register',
               'ordre' => 1,
               'created_at' => now(),
               'updated_at' => now(),
           ],
            [
               'id' => 24,
               'libelle' => 'Session Caisse Caissier',
               'libelle_en' => 'Cashier Session',
               'module_id' => 6,
               'menu_url' => 'session-caisse-caissier',
               'icone' => 'fas fa-cash-register',
               'ordre' => 2,
               'created_at' => now(),
               'updated_at' => now(),
           ],
             [
                 'id' => 25,
                 'libelle' => 'Log d\'erreur',
                 'libelle_en' => 'Error log',
                 'module_id' => 1,
                 'menu_url' => 'errorlog',
                 'icone' => 'fas fa-exclamation-triangle',
                 'ordre' => 7,
                 'created_at' => now(),
                 'updated_at' => now(),
             ],
            [
                'id' => 26,
                'libelle' => 'Ventes POS',
                'libelle_en' => 'POS sales',
                'module_id' => 6,
                'menu_url' => 'ventepos',
                'icone' => 'fas fa-cash-register',
                'ordre' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
             [
                'id' => 27,
                'libelle' => 'Mouvement stock',
                'libelle_en' => 'Stock movement',
                'module_id' => 7,
                'menu_url' => 'mouvement-stock',
                'icone' => 'fas fa-exchange-alt',
                'ordre' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 28,
                'libelle' => 'Transfert stock',
                'libelle_en' => 'Stock transfer',
                'module_id' => 7,
                'menu_url' => 'transfert-stock',
                'icone' => 'fas fa-random',
                'ordre' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 29,
                'libelle' => 'Inventaire',
                'libelle_en' => 'Inventory',
                'module_id' => 7,
                'menu_url' => 'inventaire',
                'icone' => 'fas fa-boxes',
                'ordre' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 30,
                'libelle' => 'Banques',
                'libelle_en' => 'Banks',
                'module_id' => 2,
                'menu_url' => 'banque',
                'icone' => 'fas fa-university',
                'ordre' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 31,
                'libelle' => 'Comptes Bancaires Marchand',
                'libelle_en' => 'Merchant Bank Accounts',
                'module_id' => 3,
                'menu_url' => 'compte-bancaire-marchand',
                'icone' => 'fas fa-credit-card',
                'ordre' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
             [
               'id' => 32,
               'libelle' => 'Portefeuilles',
               'libelle_en' => 'Wallets',
               'module_id' => 8,
               'menu_url' => 'wallet',
               'icone' => 'fas fa-wallet',
               'ordre' => 1,
               'created_at' => now(),
               'updated_at' => now(),
           ],

        ]);
    }
}
