<script setup>
import { computed } from 'vue';
import { useI18n } from 'vue-i18n';
import StylishSelect from '@/Components/Common/StylishSelect.vue';
import { usePermissions } from '@/Composables/usePermissions';
const { t } = useI18n();
const { can } = usePermissions();
const props = defineProps({
    form: {
        type: Object,
        required: true,
    },
    pointsVente: {
        type: Array,
        default: () => [],
    },
    types: {
        type: Array,
        default: () => [],
    },
    statuts: {
        type: Array,
        default: () => [],
    },
    mode: {
        type: String,
        default: 'create',
        validator: (value) => ['create', 'edit', 'show'].includes(value),
    },
});
const isReadOnly = computed(() => props.mode === 'show');
const isEditMode = computed(() => props.mode === 'edit');
// Computed pour traduire les labels des types
const translatedTypes = computed(() => {
    return props.types.map(type => ({
        ...type,
        label: t(`modules.business.caisses.types.${type.value}`)
    }));
});
// Computed pour traduire les labels des statuts
const translatedStatuts = computed(() => {
    return props.statuts.map(statut => ({
        ...statut,
        label: t(`modules.business.caisses.statuts.${statut.value}`)
    }));
});
</script>
<template>
    <div class="custom-input">
        <div class="row g-3">
            <!-- Point de Vente -->
            <div class="col-md-6">
                <div class="mb-3">
                    <label>{{ t('fields.pointOfSale') }}<span v-if="!isReadOnly" class="text-danger"> *</span></label>
                    <StylishSelect v-model="form.points_vente_id" :options="pointsVente" option-value="id"
                        option-label="label" :placeholder="t('actions.select') + ' ' + t('fields.pointOfSale')"
                        :disabled="isReadOnly" />
                    <span v-if="form.errors?.points_vente_id" class="text-danger">
                        <strong>{{ form.errors.points_vente_id }}</strong>
                    </span>
                </div>
            </div>
            <!-- Code -->
            <div class="col-md-6">
                <div class="mb-3">
                    <label>{{ t('fields.code') }}</label>
                    <input type="text" v-model="form.code" class="form-control"
                        :placeholder="t('fields.code') + ' (' + t('common.autoGenerated') + ')'"
                        :disabled="isReadOnly" />
                    <span v-if="form.errors?.code" class="text-danger">
                        <strong>{{ form.errors.code }}</strong>
                    </span>
                </div>
            </div>
            <!-- Nom -->
            <div class="col-md-6">
                <div class="mb-3">
                    <label>{{ t('fields.name') }}<span v-if="!isReadOnly" class="text-danger"> *</span></label>
                    <input type="text" v-model="form.nom" class="form-control" :placeholder="t('fields.name')"
                        :disabled="isReadOnly" />
                    <span v-if="form.errors?.nom" class="text-danger">
                        <strong>{{ form.errors.nom }}</strong>
                    </span>
                </div>
            </div>
            <!-- Type -->
            <div class="col-md-6">
                <div class="mb-3">
                    <label>{{ t('fields.type') }}<span v-if="!isReadOnly" class="text-danger"> *</span></label>
                    <StylishSelect v-model="form.type" :options="translatedTypes" option-value="value" option-label="label"
                        :placeholder="t('actions.select') + ' ' + t('fields.type')" :disabled="isReadOnly" />
                    <span v-if="form.errors?.type" class="text-danger">
                        <strong>{{ form.errors.type }}</strong>
                    </span>
                </div>
            </div>
            <!-- Statut (only in edit mode) -->
            <div class="col-md-6" v-if="can('caisse-statut') && (isEditMode || isReadOnly)">
                <div class="mb-3">
                    <label>{{ t('common.status') }}<span v-if="isEditMode" class="text-danger"> *</span></label>
                    <StylishSelect v-model="form.statut" :options="translatedStatuts" option-value="value" option-label="label"
                        :placeholder="t('actions.select') + ' ' + t('common.status')" :disabled="isReadOnly" />
                    <span v-if="form.errors?.statut" class="text-danger">
                        <strong>{{ form.errors.statut }}</strong>
                    </span>
                </div>
            </div>
            <!-- Paramètres JSON -->
            <div class="col-md-12">
                <div class="mb-3">
                    <label>{{ t('fields.parameters') }}</label>
                    <textarea v-model="form.parametres_json" class="form-control" :placeholder="t('fields.parameters')"
                        :disabled="isReadOnly" rows="3"></textarea>
                    <small class="text-muted">Format JSON: {"key": "value"}</small>
                    <span v-if="form.errors?.parametres_json" class="text-danger">
                        <strong>{{ form.errors.parametres_json }}</strong>
                    </span>
                </div>
            </div>
        </div>
    </div>
</template>
