<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/**
 * Import du plan comptable OHADA (ecoles) dans plan_comptes.
 * Donnees embarquees (genere depuis 'Plan comptable Ecoles OHADA.xlsx') pour
 * etre rejoue par migrate --force au deploiement, sans dependre du fichier.
 * Idempotent : n'insere que les numeros de compte absents.
 */
return new class extends Migration
{
    public function up(): void
    {
        if (!Schema::hasTable('plan_comptes')) { return; }

        $comptes = [
            ['1', 'Comptes de ressources durables', null],
            ['10', 'Capital', '1'],
            ['101', 'Capital social', '10'],
            ['1011', 'Capital souscrit, non appelé', '101'],
            ['1012', 'Capital souscrit, appelé non versé', '101'],
            ['1013', 'Capital souscrit, appelé, versé, non amorti', '101'],
            ['1014', 'Capital souscrit, appelé, versé, amorti', '101'],
            ['1018', 'Capital souscrit soumis à des conditions particulières', '101'],
            ['102', 'Capital par dotation', '10'],
            ['1021', 'Dotation initiale', '102'],
            ['1022', 'Dotations complémentaires', '102'],
            ['1028', 'Autres dotations', '102'],
            ['103', 'Capital personnel', '10'],
            ['104', 'Capital de l\'exploitation', '10'],
            ['1041', 'Apports temporaires', '104'],
            ['1042', 'Opérations courantes', '104'],
            ['1043', 'Rémunérations, impôts et autres charges personnelles', '104'],
            ['1047', 'Prélèvement d\'autoconsommation', '104'],
            ['1048', 'Autres prélèvements', '104'],
            ['105', 'Primes liées aux capital social', '10'],
            ['1051', 'Primes d\'émission', '105'],
            ['1052', 'Primes d\'apport', '105'],
            ['1053', 'Primes de fusion', '105'],
            ['1054', 'Primes de conversion', '105'],
            ['1058', 'Autres primes', '105'],
            ['106', 'Écarts de réévaluation', '10'],
            ['1061', 'Ecarts de réévaluation légale', '106'],
            ['1062', 'Ecarts de réévaluation libre', '106'],
            ['109', 'Actionnaires, capital souscrit, non appelé', '10'],
            ['11', 'Réserves', '1'],
            ['111', 'Réserve légale', '11'],
            ['112', 'Réserves statutaires ou contractuelles', '11'],
            ['113', 'Réserves réglementées', '11'],
            ['1131', 'Réserves de plus-values nettes à long terme', '113'],
            ['1132', 'Réserves d\'attribution gratuite d\'actions au personnel salarié et aux dirigeants', '113'],
            ['1133', 'Réserves consécutives à l\'octroi de subventions d\'investissement', '113'],
            ['1134', 'Réserves de valeurs mobilières donnant accès au capital', '113'],
            ['1138', 'Autres réserves réglementées', '113'],
            ['118', 'Autres réserves', '11'],
            ['1181', 'Réserves facultatives', '118'],
            ['1188', 'Réserves diverses', '118'],
            ['12', 'Report à nouveau', '1'],
            ['121', 'Report à nouveau créditeur', '12'],
            ['129', 'Report à nouveau débiteur', '12'],
            ['1291', 'Perte nette à reporter', '129'],
            ['1292', 'Perte - Amortissements réputés différés', '129'],
            ['13', 'Résultat net de l\'exercice', '1'],
            ['130', 'Résultat en instance d’affectation', '13'],
            ['1301', 'Résultat en instance d\'affectation : Bénéfice', '130'],
            ['1309', 'Résultat en instance d\'affectation : Perte', '130'],
            ['131', 'Résultat net : Bénéfice', '13'],
            ['132', 'Marge commerciale (MC)', '13'],
            ['133', 'Valeur ajoutée (VA)', '13'],
            ['134', 'Excédent brut d\'exploitation (E.B.E.)', '13'],
            ['135', 'Résultat d\'exploitation (R.E.)', '13'],
            ['136', 'Résultat financier (R.F.)', '13'],
            ['137', 'Résultat des activités ordinaires (R.A.O.)', '13'],
            ['138', 'Résultat hors activités ordinaires (R.H.A.O.)', '13'],
            ['1381', 'Résultat de fusion', '138'],
            ['1382', 'Résultat d\'apport partiel d\'actif', '138'],
            ['1383', 'Résultat de scission', '138'],
            ['1384', 'Résultat de liquidation', '138'],
            ['139', 'Résultat net : Perte', '13'],
            ['14', 'Subventions d\'investissement', '1'],
            ['141', 'Subventions d\'équipement', '14'],
            ['1411', 'État', '141'],
            ['1412', 'Régions', '141'],
            ['1413', 'Départements', '141'],
            ['1414', 'Communes et collectivités publiques décentralisées', '141'],
            ['1415', 'Entités publiques ou mixtes', '141'],
            ['1416', 'Entités et organismes privés', '141'],
            ['1417', 'Organismes internationaux', '141'],
            ['1418', 'Autres', '141'],
            ['148', 'Autres subventions d\'investissement', '14'],
            ['15', 'Provisions réglementées et fonds assimilés', '1'],
            ['151', 'Amortissements dérogatoires', '15'],
            ['152', 'Plus-values de cession à réinvestir', '15'],
            ['153', 'Fonds réglementés', '15'],
            ['1531', 'Fonds National', '153'],
            ['1532', 'Prélèvement pour le Budget', '153'],
            ['154', 'Provision spéciale de réévaluation', '15'],
            ['155', 'Provisions réglementées relatives aux immobilisations', '15'],
            ['1551', 'Reconstitution des gisements miniers et pétroliers', '155'],
            ['156', 'Provisions réglementées relatives aux stocks', '15'],
            ['1561', 'Hausse de prix', '156'],
            ['1562', 'Fluctuation des cours', '156'],
            ['157', 'Provisions pour investissement', '15'],
            ['158', 'Autres provisions et fonds réglementes', '15'],
            ['16', 'Emprunts et dettes assimilées', '1'],
            ['161', 'Emprunts obligataires', '16'],
            ['1611', 'Emprunts obligataires ordinaires', '161'],
            ['1612', 'Emprunts obligataires convertibles en actions', '161'],
            ['1613', 'Emprunts obligataires remboursables en actions', '161'],
            ['1618', 'Autres emprunts obligataires', '161'],
            ['162', 'Emprunts et dettes auprès des établissements de crédit', '16'],
            ['163', 'Avances reçues de l\'état', '16'],
            ['164', 'Avances reçues et comptes courants bloqués', '16'],
            ['165', 'Dépôts et cautionnements reçus', '16'],
            ['1651', 'Dépôts', '165'],
            ['1652', 'Cautionnements', '165'],
            ['166', 'Intérêts courus', '16'],
            ['1661', 'sur emprunts obligataires', '166'],
            ['1662', 'sur emprunts et dettes auprès des établissements de crédit', '166'],
            ['1663', 'sur avances reçues de l\'État', '166'],
            ['1664', 'sur avances reçues et comptes courants bloqués', '166'],
            ['1665', 'sur dépôts et cautionnements reçus', '166'],
            ['1667', 'sur avances assorties de conditions particulières', '166'],
            ['1668', 'sur autres emprunts et dettes', '166'],
            ['167', 'Avances assorties de conditions particulières', '16'],
            ['1671', 'Avances bloquées pour augmentation du capital', '167'],
            ['1672', 'Avances conditionnées par l\'État', '167'],
            ['1673', 'Avances conditionnées par les autres organismes africains', '167'],
            ['1674', 'Avances conditionnées par les organismes internationaux', '167'],
            ['168', 'Autres emprunts et dettes', '16'],
            ['1681', 'Rentes viagères capitalisées', '168'],
            ['1682', 'Billets de fonds', '168'],
            ['1683', 'Dettes consécutives à des titres empruntés', '168'],
            ['1684', 'Emprunts participatifs', '168'],
            ['1685', 'Participation des travailleurs aux bénéfices', '168'],
            ['1686', 'Emprunts et dettes contractés auprès des autres tiers', '168'],
            ['17', 'Dettes de location acquisition', '1'],
            ['172', 'Dettes de location acquisition/crédit-bail immobilier', '17'],
            ['173', 'Dettes de location acquisition/crédit-bail mobilier', '17'],
            ['174', 'Dettes de location acquisition/location-vente', '17'],
            ['176', 'Intérêts courus', '17'],
            ['1762', 'sur dettes de location acquisition/crédit – bail immobilier', '176'],
            ['1763', 'sur dettes de location acquisition/crédit – bail mobilier', '176'],
            ['1764', 'sur dettes de location acquisition/location-vente', '176'],
            ['1768', 'sur autres dettes de location acquisition', '176'],
            ['178', 'Autres dettes de location acquisition', '17'],
            ['18', 'Dettes liées à des participations et comptes de liaison des établissements et sociétés en participation', '1'],
            ['181', 'Dettes liées à des participations', '18'],
            ['1811', 'Dettes liées à des participations (groupe)', '181'],
            ['1812', 'Dettes liées à des participations (hors groupe)', '181'],
            ['182', 'Dettes liées à des sociétés en participation', '18'],
            ['183', 'Intérêts courus sur dettes liées à des participations', '18'],
            ['184', 'Comptes permanents bloqués des établissements et succursales', '18'],
            ['185', 'Comptes permanents non bloqués des établissements et succursales', '18'],
            ['186', 'Comptes de liaison charges', '18'],
            ['187', 'Comptes de liaison produits', '18'],
            ['188', 'Comptes de liaison des sociétés en participation', '18'],
            ['19', 'Provisions pour risques et charges', '1'],
            ['191', 'Provisions pour litiges', '19'],
            ['192', 'Provisions pour garanties données aux Apprenants et familles', '19'],
            ['193', 'Provisions pour pertes sur marchés à achèvement futur', '19'],
            ['194', 'Provisions pour pertes de change', '19'],
            ['195', 'Provisions pour impôts', '19'],
            ['196', 'Provisions pour pensions et obligations similaires', '19'],
            ['1961', 'Provisions pour pensions et obligations similaires - engagement de retraite', '196'],
            ['1962', 'Actifs du régime de retraite', '196'],
            ['197', 'Provisions pour restructuration', '19'],
            ['198', 'Autres provisions pour risques et charges', '19'],
            ['1981', 'Provisions pour amendes et pénalités', '198'],
            ['1983', 'Provisions de propre assureur', '198'],
            ['1984', 'Provisions pour démantèlement et remise en l\'état', '198'],
            ['1985', 'Provisions pour droits à réduction ou avantage en nature (Chèques, cadeaux, cartes de fidélité …)', '198'],
            ['1988', 'Provisions pour divers risques et charges', '198'],
            ['2', 'Comptes d\'actif immobilisé', null],
            ['21', 'Immobilisations incorporelles', '2'],
            ['211', 'Frais de développement', '21'],
            ['212', 'Brevets, licences, concessions et droits similaires', '21'],
            ['2121', 'Brevets', '212'],
            ['2122', 'Licences', '212'],
            ['2123', 'Concessions de service public', '212'],
            ['2128', 'Autres concessions et droits similaires', '212'],
            ['213', 'Logiciels et sites internet', '21'],
            ['2131', 'Logiciels', '213'],
            ['2132', 'Sites internet', '213'],
            ['214', 'Marques', '21'],
            ['215', 'Fonds commercial', '21'],
            ['216', 'Droit au bail', '21'],
            ['217', 'Investissements de création', '21'],
            ['218', 'Autres droits et valeurs incorporels', '21'],
            ['2181', 'Frais de prospection et d\'évaluation de ressources minérales', '218'],
            ['2182', 'Coûts d\'obtention du contrat', '218'],
            ['2183', 'Fichiers Apprenants et familles, notices, titres de journaux et magazines', '218'],
            ['2184', 'Coûts des franchises', '218'],
            ['2188', 'Divers droits et valeurs incorporels', '218'],
            ['219', 'Immobilisations incorporelles en cours', '21'],
            ['2191', 'Frais de développement', '219'],
            ['2193', 'Logiciels et internet', '219'],
            ['2198', 'Autres droits et valeurs incorporels', '219'],
            ['22', 'Terrains', '2'],
            ['221', 'Terrains agricoles et forestiers', '22'],
            ['2211', 'Terrains d\'exploitation agricole', '221'],
            ['2212', 'Terrains d\'exploitation forestière', '221'],
            ['2218', 'Autres terrains', '221'],
            ['222', 'Terrains nus', '22'],
            ['2221', 'Terrains à bâtir', '222'],
            ['2228', 'Autres terrains nus', '222'],
            ['223', 'Terrains bâtis', '22'],
            ['2231', 'pour bâtiments industriels et agricoles', '223'],
            ['2232', 'pour bâtiments administratifs et commerciaux', '223'],
            ['2234', 'pour bâtiments affectés aux autres opérations professionnelles', '223'],
            ['2235', 'pour bâtiments affectés aux autres opérations non professionnelles', '223'],
            ['2238', 'Autres terrains bâtis', '223'],
            ['224', 'Travaux de mise en valeur des terrains', '22'],
            ['2241', 'Plantation d\'arbres et d\'arbustes', '224'],
            ['2245', 'Amélioration du fonds', '224'],
            ['2248', 'Autres travaux', '224'],
            ['225', 'Terrains de carrière - tréfonds', '22'],
            ['2251', 'Carrières', '225'],
            ['226', 'Terrains aménagés', '22'],
            ['2261', 'Parkings', '226'],
            ['227', 'Terrains mis en concession', '22'],
            ['228', 'Autres terrains', '22'],
            ['2281', 'Terrains - immeubles de placement', '228'],
            ['2285', 'Terrains des logements affectés au personnel', '228'],
            ['2286', 'Terrains de location - acquisition', '228'],
            ['2288', 'Divers terrains', '228'],
            ['229', 'Aménagements de terrains en cours', '22'],
            ['2291', 'Terrains agricoles et forestiers', '229'],
            ['2292', 'Terrains nus', '229'],
            ['2295', 'Terrains de carrières - tréfonds', '229'],
            ['2298', 'Autres terrains', '229'],
            ['23', 'Bâtiments, installations techniques et agencements', '2'],
            ['231', 'Bâtiments industriels, agricoles, administratifs et commerciaux sur sol propre', '23'],
            ['2311', 'Bâtiments industriels', '231'],
            ['2312', 'Bâtiments agricoles', '231'],
            ['2313', 'Bâtiments administratifs et commerciaux', '231'],
            ['2314', 'Bâtiments affectés au logement du personnel', '231'],
            ['2315', 'Bâtiments - immeubles de placement', '231'],
            ['2316', 'Bâtiments de location - acquisition', '231'],
            ['232', 'Bâtiments industriels, agricoles, administratifs et commerciaux sur sol d’autrui', '23'],
            ['2321', 'Bâtiments industriels', '232'],
            ['2322', 'Bâtiments agricoles', '232'],
            ['2323', 'Bâtiments administratifs et commerciaux', '232'],
            ['2324', 'Bâtiments affectés au logement du personnel', '232'],
            ['2325', 'Bâtiments - immeubles de placement', '232'],
            ['2326', 'Bâtiments de location - acquisition', '232'],
            ['233', 'Ouvrages d’infrastructure', '23'],
            ['2331', 'Voies de terre', '233'],
            ['2332', 'Voies de fer', '233'],
            ['2333', 'Voies d’eau', '233'],
            ['2334', 'Barrages, Digues', '233'],
            ['2335', 'Pistes d’aérodrome', '233'],
            ['2338', 'Autres ouvrages d\'infrastructures', '233'],
            ['234', 'Aménagements, agencements et installations techniques', '23'],
            ['2341', 'Installations complexes spécialisées sur sol propre', '234'],
            ['2342', 'Installations complexes spécialisées sur sol d’autrui', '234'],
            ['2343', 'Installations à caractère spécifique sur sol propre', '234'],
            ['2344', 'Installations à caractère spécifique sur sol d’autrui', '234'],
            ['2345', 'Aménagements et agencements des bâtiments', '234'],
            ['235', 'Aménagements de bureaux', '23'],
            ['2351', 'Installations générales', '235'],
            ['2358', 'Autres aménagements de bureaux', '235'],
            ['237', 'Bâtiments industriels, agricoles et commerciaux mis en concession', '23'],
            ['238', 'Autres installations et agencements', '23'],
            ['239', 'Bâtiments, aménagements, agencements et installations en cours', '23'],
            ['2391', 'Bâtiments en cours', '239'],
            ['2392', 'Installations en cours', '239'],
            ['2393', 'Ouvrages d\'infrastructure en cours', '239'],
            ['2394', 'Aménagements, agencements, et installations techniques en cours', '239'],
            ['2395', 'Aménagements de bureaux en cours', '239'],
            ['2398', 'Autres installations et agencements en cours', '239'],
            ['24', 'Matériel, mobilier et actifs biologiques', '2'],
            ['241', 'Matériel et outillage industriel et commercial', '24'],
            ['2411', 'Matériel industriel', '241'],
            ['2412', 'Outillage industriel', '241'],
            ['2413', 'Matériel commercial', '241'],
            ['2414', 'Outillage commercial', '241'],
            ['2416', 'Matériel et outillage industriel et commercial de location - acquisition', '241'],
            ['242', 'Matériel et outillage agricole', '24'],
            ['2421', 'Matériel agricole', '242'],
            ['2422', 'Outillage agricole', '242'],
            ['2426', 'Matériel et outillage agricole de location - acquisition', '242'],
            ['243', 'Matériel d’emballage récupérable et identifiable', '24'],
            ['244', 'Matériel et mobilier', '24'],
            ['2441', 'Matériel de bureau', '244'],
            ['2442', 'Matériel informatique', '244'],
            ['2443', 'Matériel bureautique', '244'],
            ['2444', 'Mobilier de bureau', '244'],
            ['2445', 'Matériel et mobilier- immeubles de placement', '244'],
            ['2446', 'Matériel et mobilier de location - acquisition', '244'],
            ['2447', 'Matériel et mobilier des logements du personnel', '244'],
            ['245', 'Matériel de transport', '24'],
            ['2451', 'Matériel automobile', '245'],
            ['2452', 'Matériel ferroviaire', '245'],
            ['2453', 'Matériel fluvial, lagunaire', '245'],
            ['2454', 'Matériel naval', '245'],
            ['2455', 'Matériel aérien', '245'],
            ['2456', 'Matériel de transport de location - acquisition', '245'],
            ['2457', 'Matériel hippomobile', '245'],
            ['2458', 'Autres matériels de transport (vélo, mobylette, moto …)', '245'],
            ['246', 'Actifs biologiques', '24'],
            ['2461', 'Cheptel, animaux de trait', '246'],
            ['2462', 'Cheptel, animaux reproducteurs', '246'],
            ['2463', 'Animaux de garde', '246'],
            ['2465', 'Plantations agricoles', '246'],
            ['2468', 'Autres actifs biologiques', '246'],
            ['247', 'Agencements, aménagements du matériel et actifs biologiques', '24'],
            ['2471', 'Agencements et aménagements du matériel', '247'],
            ['2472', 'Agencements et aménagements des actifs biologiques', '247'],
            ['2478', 'Autres agencements et aménagements du matériel et actifs biologiques', '247'],
            ['248', 'Autres matériels et mobiliers', '24'],
            ['2481', 'Collections et œuvres d’art', '248'],
            ['2482', 'Divers matériels mobiliers', '248'],
            ['249', 'Matériels et actifs biologiques en cours', '24'],
            ['2491', 'Matériel et outillage industriel et commercial', '249'],
            ['2492', 'Matériel et outillage agricole', '249'],
            ['2493', 'Matériel d’emballage récupérable et identifiable', '249'],
            ['2494', 'Matériel et mobilier de bureau', '249'],
            ['2495', 'Matériel de transport', '249'],
            ['2496', 'Actifs biologiques', '249'],
            ['2497', 'Agencements et aménagements du matériel et des actifs biologiques', '249'],
            ['2498', 'Autres matériels et actifs biologiques en cours', '249'],
            ['25', 'Avances et acomptes versés sur immobilisations', '2'],
            ['251', 'Avances et acomptes versés sur immobilisations incorporelles', '25'],
            ['252', 'Avances et acomptes versés sur immobilisations corporelles', '25'],
            ['26', 'Titres de participation', '2'],
            ['261', 'Titres de participation dans des sociétés sous contrôle exclusif', '26'],
            ['262', 'Titres de participation dans des sociétés sous contrôle conjoint', '26'],
            ['263', 'Titres de participation dans des sociétés conférant une influence notable', '26'],
            ['265', 'Participations dans des organismes professionnels', '26'],
            ['266', 'Parts dans des groupements d’intérêt économique (G.I.E.)', '26'],
            ['268', 'Autres titres de participation', '26'],
            ['27', 'Autres immobilisations financières', '2'],
            ['271', 'Prêts et créances', '27'],
            ['2711', 'Prêts participatifs', '271'],
            ['2712', 'Prêts aux associés', '271'],
            ['2713', 'Billets de fonds', '271'],
            ['2714', 'Titres prêtés', '271'],
            ['2718', 'Autres prêts et créances', '271'],
            ['272', 'Prêts au personnel', '27'],
            ['2721', 'Prêts immobiliers', '272'],
            ['2722', 'Prêts mobiliers et d’installation', '272'],
            ['2728', 'Autres prêts au personnel (frais d’études…)', '272'],
            ['273', 'Créances sur l’état', '27'],
            ['2731', 'Retenues de garantie', '273'],
            ['2733', 'Fonds réglementé', '273'],
            ['2734', 'Créances sur le concédant', '273'],
            ['2738', 'Autres créances sur l’État', '273'],
            ['274', 'Titres immobilisés', '27'],
            ['2741', 'Titres immobilisés de l’activité de portefeuille (T.I.A.P)', '274'],
            ['2742', 'Titres participatifs', '274'],
            ['2743', 'Certificats d’investissement', '274'],
            ['2744', 'Parts de fonds commun de placement (F.C.P.)', '274'],
            ['2745', 'Obligations', '274'],
            ['2746', 'Actions ou parts propres', '274'],
            ['2748', 'Autres titres immobilisés', '274'],
            ['275', 'Dépôts et cautionnements versés', '27'],
            ['2751', 'Dépôts pour loyers d’avance', '275'],
            ['2752', 'Dépôts pour l’électricité', '275'],
            ['2753', 'Dépôts pour l’eau', '275'],
            ['2754', 'Dépôts pour le gaz', '275'],
            ['2755', 'Dépôts pour le téléphone, le télex, la télécopie', '275'],
            ['2756', 'Cautionnements sur marchés publics', '275'],
            ['2757', 'Cautionnements sur autres opérations', '275'],
            ['2758', 'Autres dépôts et cautionnements', '275'],
            ['276', 'Intérêts courus', '27'],
            ['2761', 'Prêts et créances non commerciales', '276'],
            ['2762', 'Prêts au personnel', '276'],
            ['2763', 'Créances sur l\'Etat', '276'],
            ['2764', 'Titres immobilisés', '276'],
            ['2765', 'Dépôts et cautionnements versés', '276'],
            ['2767', 'Créances rattachées à des participations', '276'],
            ['2768', 'Immobilisations financières diverses', '276'],
            ['277', 'Créances rattachées à des participations et avances à des G.I.E.', '27'],
            ['2771', 'Créances rattachées à des participations (groupe)', '277'],
            ['2772', 'Créances rattachées à des participations (hors groupe)', '277'],
            ['2773', 'Créances rattachées à des sociétés en participation', '277'],
            ['2774', 'Avances à des Groupements d\'intérêt économique (G.I.E.)', '277'],
            ['278', 'Immobilisations financières diverses', '27'],
            ['2781', 'Créances diverses groupe', '278'],
            ['2782', 'Créances diverses hors groupe', '278'],
            ['2784', 'Banques dépôts à terme', '278'],
            ['2785', 'Or et métaux précieux', '278'],
            ['2788', 'Autres immobilisations financières', '278'],
            ['28', 'Amortissements', '2'],
            ['281', 'Amortissements des immobilisations incorporelles', '28'],
            ['2811', 'Amortissements des frais de développement', '281'],
            ['2812', 'Amortissements des brevets, licences, concessions et droits similaires', '281'],
            ['2813', 'Amortissements des logiciels et sites internet', '281'],
            ['2814', 'Amortissements des marques', '281'],
            ['2815', 'Amortissements du fonds commercial', '281'],
            ['2816', 'Amortissements du droit au bail', '281'],
            ['2817', 'Amortissements des investissements de création', '281'],
            ['2818', 'Amortissements des autres droits et valeurs incorporels', '281'],
            ['282', 'Amortissements des terrains', '28'],
            ['2824', 'Amortissements des travaux de mise en valeur des terrains', '282'],
            ['283', 'Amortissements des bâtiments, installations techniques et agencements', '28'],
            ['2831', 'Amortissements des bâtiments industriels, agricoles, administratifs et commerciaux sur sol propre', '283'],
            ['2832', 'Amortissements des bâtiments industriels, agricoles, administratifs et commerciaux sur sol d\'autrui', '283'],
            ['2833', 'Amortissements des ouvrages d\'infrastructure', '283'],
            ['2834', 'Amortissements des aménagements, agencements et installations techniques', '283'],
            ['2835', 'Amortissements des aménagements de bureaux', '283'],
            ['2837', 'Amortissements des bâtiments industriels, agricoles et commerciaux mis en concession', '283'],
            ['2838', 'Amortissements des autres installations et agencements', '283'],
            ['284', 'Amortissements du matériel', '28'],
            ['2841', 'Amortissements du matériel et outillage industriel et commercial', '284'],
            ['2842', 'Amortissements du matériel et outillage agricole', '284'],
            ['2843', 'Amortissements du matériel d\'emballage récupérable et identifiable', '284'],
            ['2844', 'Amortissements du matériel et mobilier', '284'],
            ['2845', 'Amortissements du matériel de transport', '284'],
            ['2846', 'Amortissements des actifs biologiques', '284'],
            ['2847', 'Amortissements des agencements et aménagements du matériel et des actifs biologiques', '284'],
            ['2848', 'Amortissements des autres matériels', '284'],
            ['29', 'Dépréciations des immobilisations', '2'],
            ['291', 'Dépréciation des immobilisations incorporelles', '29'],
            ['2911', 'Dépréciation des frais de développement', '291'],
            ['2912', 'Dépréciation des brevets, licences, concessions et droits similaires', '291'],
            ['2913', 'Dépréciation des logiciels et sites internet', '291'],
            ['2914', 'Dépréciation des marques', '291'],
            ['2915', 'Dépréciation du fonds commercial', '291'],
            ['2916', 'Dépréciation du droit au bail', '291'],
            ['2917', 'Dépréciation des investissements de création', '291'],
            ['2918', 'Dépréciation des autres droits et valeurs incorporels', '291'],
            ['2919', 'Dépréciation des immobilisations incorporelles en cours', '291'],
            ['292', 'Dépréciation des terrains', '29'],
            ['2921', 'Dépréciation des terrains agricoles et forestiers', '292'],
            ['2922', 'Dépréciation des terrains nus', '292'],
            ['2923', 'Dépréciation des terrains bâtis', '292'],
            ['2924', 'Dépréciation des travaux de mise en valeur des terrains', '292'],
            ['2925', 'Dépréciation des terrains de gisement (Carrières - tréfonds)', '292'],
            ['2926', 'Dépréciation des terrains aménagés', '292'],
            ['2927', 'Dépréciation des terrains mis en concession', '292'],
            ['2928', 'Dépréciation des autres terrains', '292'],
            ['2929', 'Dépréciation des aménagements de terrains en cours', '292'],
            ['293', 'Dépréciation des bâtiments, installations techniques et agencements', '29'],
            ['2931', 'Dépréciation des bâtiments industriels, agricoles, administratifs et commerciaux sur sol propre', '293'],
            ['2932', 'Dépréciation des bâtiments industriels, agricoles, administratifs et commerciaux sur sol d\'autrui', '293'],
            ['2933', 'Dépréciation des ouvrages d\'infrastructures', '293'],
            ['2934', 'Dépréciation des aménagements, agencements et installations techniques', '293'],
            ['2935', 'Dépréciation des aménagements de bureaux', '293'],
            ['2937', 'Dépréciation des bâtiments industriels, agricoles et commerciaux mis en concession', '293'],
            ['2938', 'Dépréciation des autres installations et agencements', '293'],
            ['2939', 'Dépréciation des bâtiments et installations en cours', '293'],
            ['294', 'Dépréciation de matériel', '29'],
            ['2941', 'Dépréciation du matériel et outillage industriel et commercial', '294'],
            ['2942', 'Dépréciation du matériel et outillage agricole', '294'],
            ['2943', 'Dépréciation du matériel d\'emballage récupérable et identifiable', '294'],
            ['2944', 'Dépréciation du matériel et mobilier', '294'],
            ['2945', 'Dépréciation du matériel de transport', '294'],
            ['2946', 'Dépréciation des actifs biologiques', '294'],
            ['2947', 'Dépréciation des agencements et aménagements du matériel et des actifs biologiques', '294'],
            ['2948', 'Dépréciation des autres matériels', '294'],
            ['2949', 'Dépréciation de matériel en cours', '294'],
            ['295', 'Dépréciation des avances et acomptes versés sur immobilisations', '29'],
            ['2951', 'Dépréciation des avances et acomptes versés sur immobilisations incorporelles', '295'],
            ['2952', 'Dépréciation des avances et acomptes versés sur immobilisations corporelles', '295'],
            ['296', 'Dépréciation des titres de participation', '29'],
            ['2961', 'Dépréciation des titres de participation dans des sociétés sous contrôle exclusif', '296'],
            ['2962', 'Dépréciation des titres de participation dans les sociétés sous contrôle conjoint', '296'],
            ['2963', 'Dépréciation des titres de participation dans les sociétés conférant une influence notable', '296'],
            ['2965', 'Dépréciation des participations dans des organismes professionnels', '296'],
            ['2966', 'Dépréciation des parts dans des GIE', '296'],
            ['2968', 'Dépréciation des autres titres de participation', '296'],
            ['297', 'Dépréciation des autres immobilisations financières', '29'],
            ['2971', 'Dépréciation des prêts et créances', '297'],
            ['2972', 'Dépréciation des prêts au personnel', '297'],
            ['2973', 'Dépréciation des créances sur l\'Etat', '297'],
            ['2974', 'Dépréciation des titres immobilisés', '297'],
            ['2975', 'Dépréciation des dépôts et cautionnements versés', '297'],
            ['2977', 'Dépréciation des créances rattachées à des participations et avances à des GIE', '297'],
            ['2978', 'Dépréciation des créances financières diverses', '297'],
            ['3', 'Comptes de stocks', null],
            ['31', 'Marchandises', '3'],
            ['311', 'Marchandises A', '31'],
            ['3111', 'Marchandises A1', '311'],
            ['3112', 'Marchandises A2', '311'],
            ['312', 'Marchandises B', '31'],
            ['3121', 'Marchandises B1', '312'],
            ['3122', 'Marchandises B2', '312'],
            ['313', 'Actifs biologiques', '31'],
            ['3131', 'Animaux', '313'],
            ['3132', 'Végétaux', '313'],
            ['318', 'Marchandises hors activités ordinaires (H.A.O.)', '31'],
            ['32', 'Matières premières et fournitures liées', '3'],
            ['321', 'Matières A', '32'],
            ['322', 'Matières B', '32'],
            ['323', 'Fournitures (A, B)', '32'],
            ['33', 'Autres approvisionnements', '3'],
            ['331', 'Matières consommables', '33'],
            ['332', 'Fournitures d\'atelier et d\'usine', '33'],
            ['333', 'Fournitures de magasin', '33'],
            ['334', 'Fournitures de bureau', '33'],
            ['335', 'Emballages', '33'],
            ['3351', 'Emballages perdus', '335'],
            ['3352', 'Emballages récupérables non identifiables', '335'],
            ['3353', 'Emballages à usage mixte', '335'],
            ['3358', 'Autres emballages', '335'],
            ['338', 'Autres matières', '33'],
            ['34', 'Produits en cours', '3'],
            ['341', 'Produits en cours', '34'],
            ['3411', 'Produits en cours P1', '341'],
            ['3412', 'Produits en cours P2', '341'],
            ['342', 'Travaux en cours', '34'],
            ['3421', 'Travaux en cours T1', '342'],
            ['3422', 'Travaux en cours T2', '342'],
            ['343', 'Produits intermédiaires en cours', '34'],
            ['3431', 'Produits intermédiaires A', '343'],
            ['3432', 'Produits intermédiaires B', '343'],
            ['344', 'Produits résiduels en cours', '34'],
            ['3441', 'Produits résiduels A', '344'],
            ['3442', 'Produits résiduels B', '344'],
            ['345', 'Actifs biologiques en cours', '34'],
            ['3451', 'Animaux', '345'],
            ['3452', 'Végétaux', '345'],
            ['35', 'Services en cours', '3'],
            ['351', 'Études en cours', '35'],
            ['3511', 'Études en cours E1', '351'],
            ['3512', 'Études en cours E2', '351'],
            ['352', 'Prestations de services en cours', '35'],
            ['3521', 'Prestations de services S1', '352'],
            ['3522', 'Prestations de services S2', '352'],
            ['36', 'Produits finis', '3'],
            ['361', 'Produits finis A', '36'],
            ['362', 'Produits finis B', '36'],
            ['363', 'Actifs biologiques', '36'],
            ['3631', 'Animaux', '363'],
            ['3632', 'Végétaux', '363'],
            ['3638', 'Autres stocks (activités annexes)', '363'],
            ['37', 'Produits intermédiaires et résiduels', '3'],
            ['371', 'Produits intermédiaires', '37'],
            ['3711', 'Produits intermédiaires A', '371'],
            ['3712', 'Produits intermédiaires B', '371'],
            ['372', 'Produits résiduels', '37'],
            ['3721', 'Déchets', '372'],
            ['3722', 'Rebuts', '372'],
            ['3723', 'Matières de Récupération', '372'],
            ['373', 'Actifs biologiques', '37'],
            ['3731', 'Animaux', '373'],
            ['3732', 'Végétaux', '373'],
            ['3738', 'Autres stocks (activités annexes)', '373'],
            ['38', 'Stocks en cours de route, en consignation ou en dépôt', '3'],
            ['381', 'Marchandises en cours de route', '38'],
            ['382', 'Matières premières et fournitures liées en cours de route', '38'],
            ['383', 'Autres approvisionnements en cours de route', '38'],
            ['386', 'Produits finis en cours de route', '38'],
            ['387', 'Stock en consignation ou en dépôt', '38'],
            ['3871', 'Stock en consignation', '387'],
            ['3872', 'Stock en dépôt', '387'],
            ['388', 'Stock provenant d\'immobilisations mises hors service ou au rebut', '38'],
            ['39', 'Dépréciations des stocks et encours de production', '3'],
            ['391', 'Dépréciations des stocks de marchandises', '39'],
            ['392', 'Dépréciations des stocks de matières premières et fournitures liées', '39'],
            ['393', 'Dépréciations des stocks d\'autres approvisionnements', '39'],
            ['394', 'Dépréciations des productions en cours', '39'],
            ['395', 'Dépréciations des services en cours', '39'],
            ['396', 'Dépréciations des stocks de produits finis', '39'],
            ['397', 'Dépréciations des stocks de produits intermédiaires et résiduels', '39'],
            ['398', 'Dépréciations des stocks en cours de route, en consignation ou en dépôt', '39'],
            ['4', 'Comptes de tiers', null],
            ['40', 'Fournisseurs et comptes rattachés', '4'],
            ['401', 'Fournisseurs, dettes en compte', '40'],
            ['4011', 'Fournisseurs', '401'],
            ['4012', 'Fournisseurs Groupe', '401'],
            ['4013', 'Fournisseurs sous-traitants', '401'],
            ['4016', 'Fournisseurs, réserve de propriété', '401'],
            ['4017', 'Fournisseurs, retenues de garantie', '401'],
            ['402', 'Fournisseurs, effets à payer', '40'],
            ['4021', 'Fournisseurs, Effets à payer', '402'],
            ['4022', 'Fournisseurs - Groupe, Effets à payer', '402'],
            ['4023', 'Fournisseurs sous-traitants, Effets à payer', '402'],
            ['404', 'Fournisseurs, acquisitions courantes d\'immobilisations', '40'],
            ['4041', 'Fournisseurs dettes en compte, immobilisations incorporelles', '404'],
            ['4042', 'Fournisseurs dettes en compte, immobilisations corporelles', '404'],
            ['4046', 'Fournisseurs effets à payer, immobilisations incorporelles', '404'],
            ['4047', 'Fournisseurs effets à payer, immobilisations corporelles', '404'],
            ['408', 'Fournisseurs, factures non parvenues', '40'],
            ['4081', 'Fournisseurs', '408'],
            ['4082', 'Fournisseurs - Groupe', '408'],
            ['4083', 'Fournisseurs sous-traitants', '408'],
            ['4086', 'Fournisseurs, intérêts courus', '408'],
            ['409', 'Fournisseurs débiteurs', '40'],
            ['4091', 'Fournisseurs avances et acomptes versés', '409'],
            ['4092', 'Fournisseurs - Groupe avances et acomptes versés', '409'],
            ['4093', 'Fournisseurs sous-traitants avances et acomptes versés', '409'],
            ['4094', 'Fournisseurs créances pour emballages et matériels à rendre', '409'],
            ['4098', 'Rabais, Remises, Ristournes et autres avoirs à obtenir', '409'],
            ['41', 'Apprenants et familles et comptes rattachés', '4'],
            ['411', 'Apprenants et familles', '41'],
            ['4111', 'Apprenants et familles', '411'],
            ['4112', 'Apprenants et familles - Groupe', '411'],
            ['4114', 'Apprenants et familles, État et Collectivités publiques', '411'],
            ['4115', 'Apprenants et familles organismes internationaux', '411'],
            ['4116', 'Apprenants et familles, réserve de propriété', '411'],
            ['4117', 'Client, retenues de garantie', '411'],
            ['4118', 'Apprenants et familles, dégrèvement de Taxes sur la Valeur Ajoutée (T.V.A.)', '411'],
            ['412', 'Apprenants et familles, effets à recevoir en portefeuille', '41'],
            ['4121', 'Apprenants et familles, Effets à recevoir', '412'],
            ['4122', 'Apprenants et familles - Groupe, Effets à recevoir', '412'],
            ['4124', 'État et Collectivités publiques, Effets à recevoir', '412'],
            ['4125', 'Organismes Internationaux, Effets à recevoir', '412'],
            ['413', 'Apprenants et familles, chèques, effets et autres valeurs impayés', '41'],
            ['4131', 'Apprenants et familles, chèques impayés', '413'],
            ['4132', 'Apprenants et familles, effets impayés', '413'],
            ['4133', 'Apprenants et familles cartes de crédit impayées', '413'],
            ['4138', 'Apprenants et familles, autres valeurs impayées', '413'],
            ['414', 'Créances sur cessions courantes d\'immobilisations', '41'],
            ['4141', 'Créances en compte, immobilisations incorporelles', '414'],
            ['4142', 'Créances en compte, immobilisations corporelles', '414'],
            ['4146', 'Effets à recevoir, immobilisations incorporelles', '414'],
            ['4147', 'Effets à recevoir, immobilisations corporelles', '414'],
            ['415', 'Apprenants et familles, effets escomptés non échus', '41'],
            ['416', 'Créances Apprenants et familles litigieuses ou douteuses', '41'],
            ['4161', 'Créances litigieuses', '416'],
            ['4162', 'Créances douteuses', '416'],
            ['418', 'Apprenants et familles, produits à recevoir', '41'],
            ['4181', 'Apprenants et familles, factures à établir', '418'],
            ['4186', 'Apprenants et familles, intérêts courus', '418'],
            ['419', 'Apprenants et familles créditeurs', '41'],
            ['4191', 'Apprenants et familles, avances et acomptes reçus', '419'],
            ['4192', 'Apprenants et familles - Groupe, avances et acomptes reçus', '419'],
            ['4194', 'Apprenants et familles, dettes pour emballages et matériels consignés', '419'],
            ['4198', 'Rabais, Remises, Ristournes et autres avoirs à accorder', '419'],
            ['42', 'Personnel', '4'],
            ['421', 'Personnel, avances et acomptes', '42'],
            ['4211', 'Personnel, avances', '421'],
            ['4212', 'Personnel, acomptes', '421'],
            ['4213', 'Frais avancés et fournitures au personnel', '421'],
            ['422', 'Personnel, rémunérations dues', '42'],
            ['423', 'Personnel, oppositions, saisies-arrêts', '42'],
            ['4231', 'Personnel, oppositions', '423'],
            ['4232', 'Personnel, saisies-arrêts', '423'],
            ['4233', 'Personnel, avis à tiers détenteur', '423'],
            ['424', 'Personnel, œuvres sociales internes', '42'],
            ['4241', 'Assistance médicale', '424'],
            ['4242', 'Allocations familiales', '424'],
            ['4245', 'Organismes sociaux rattachés à l\'entité', '424'],
            ['4248', 'Autres œuvres sociales internes', '424'],
            ['425', 'Représentants du personnel', '42'],
            ['4251', 'Délégués du personnel', '425'],
            ['4252', 'Syndicats et Comités d\'entreprises, d\'Établissement', '425'],
            ['4258', 'Autres représentants du personnel', '425'],
            ['426', 'Personnel, participation aux bénéfices et au capital', '42'],
            ['4261', 'Participation aux bénéfices', '426'],
            ['4264', 'Participation au capital', '426'],
            ['427', 'Personnel – dépôts', '42'],
            ['428', 'Personnel, charges à payer et produits à recevoir', '42'],
            ['4281', 'Dettes provisionnées pour congés à payer', '428'],
            ['4286', 'Autres Charges à payer', '428'],
            ['4287', 'Produits à recevoir', '428'],
            ['43', 'Organismes sociaux', '4'],
            ['431', 'Sécurité sociale', '43'],
            ['4311', 'Prestations familiales', '431'],
            ['4312', 'Accidents de travail', '431'],
            ['4313', 'Caisse de retraite obligatoire', '431'],
            ['4314', 'Caisse de retraite facultative', '431'],
            ['4318', 'Autres cotisations sociales', '431'],
            ['432', 'Caisses de retraite complémentaire', '43'],
            ['433', 'Autres organismes sociaux', '43'],
            ['4331', 'Mutuelle', '433'],
            ['4332', 'Assurance retraite', '433'],
            ['4333', 'Assurances et organismes de santé', '433'],
            ['438', 'Organismes sociaux, charges à payer et produits à recevoir', '43'],
            ['4381', 'Charges sociales sur gratifications à payer', '438'],
            ['4382', 'Charges sociales sur congés à payer', '438'],
            ['4386', 'Autres charges à payer', '438'],
            ['4387', 'Produits à recevoir', '438'],
            ['44', 'État et collectivités publiques', '4'],
            ['441', 'État, impôt sur les bénéfices', '44'],
            ['442', 'État, autres impôts et taxes', '44'],
            ['4421', 'Impôts et taxes d\'Etat', '442'],
            ['4422', 'Impôts et taxes pour les collectivités publiques', '442'],
            ['4423', 'Impôts et taxes recouvrables sur des obligataires', '442'],
            ['4424', 'Impôts et taxes recouvrables sur des associés', '442'],
            ['4426', 'Droits de douane', '442'],
            ['4428', 'Autres impôts et taxes', '442'],
            ['443', 'État, T.V.A facturée', '44'],
            ['4431', 'T.V.A. facturée sur ventes', '443'],
            ['4432', 'T.V.A. facturée sur prestations de services', '443'],
            ['4433', 'T.V.A. facturée sur travaux', '443'],
            ['4434', 'T.V.A. facturée sur production livrée à soi-même', '443'],
            ['4435', 'T.V.A. sur factures à établir', '443'],
            ['4437', 'T.V.A. collectée sur ventes à régulariser', '443'],
            ['4439', 'T.V.A. collectée retenue à la source', '443'],
            ['444', 'État, T.V.A. due ou crédit de T.V.A', '44'],
            ['4441', 'État, T.V.A due', '444'],
            ['4449', 'Etat, crédit de T.V.A à reporter', '444'],
            ['445', 'État, T.V.A. récupérable', '44'],
            ['4451', 'T.V.A récupérable sur immobilisations', '445'],
            ['4452', 'T.V.A récupérable sur achats', '445'],
            ['4453', 'T.V.A récupérable sur transport', '445'],
            ['4454', 'T.V.A récupérable sur services extérieurs et autres charges', '445'],
            ['4455', 'T.V.A récupérable sur factures non parvenues', '445'],
            ['4456', 'T.V.A transférée par d\'autres entreprises', '445'],
            ['4455', 'T.V.A sur achats à régulariser', '445'],
            ['4457', 'T.V.A récupérable retenue à la source', '445'],
            ['446', 'État, autres taxes sur le chiffre d\'affaires', '44'],
            ['447', 'État, impôts retenus à la source', '44'],
            ['4471', 'Impôt Général sur le revenu', '447'],
            ['4472', 'Impôts sur salaires', '447'],
            ['4473', 'Contribution nationale', '447'],
            ['4474', 'Contribution nationale de solidarité', '447'],
            ['4478', 'Autres impôts et contributions', '447'],
            ['448', 'État, charges à payer et produits à recevoir', '44'],
            ['4486', 'Charges à payer', '448'],
            ['4487', 'Produits à recevoir', '448'],
            ['449', 'État, créances et dettes diverses', '44'],
            ['4491', 'État, obligations cautionnées', '449'],
            ['4492', 'État, avances et acomptes versés sur impôts', '449'],
            ['4493', 'État, fonds de dotation à recevoir', '449'],
            ['4494', 'État, subventions d\'équipement à recevoir', '449'],
            ['4495', 'État, subventions d\'exploitation à recevoir', '449'],
            ['4496', 'État, subventions d\'équilibre à recevoir', '449'],
            ['4497', 'État, avances sur subventions', '449'],
            ['4499', 'État, fonds réglementés provisionnés', '449'],
            ['45', 'Organismes internationaux', '4'],
            ['451', 'Opérations avec les organismes africains', '45'],
            ['452', 'Opérations avec les autres organismes internationaux', '45'],
            ['458', 'Organismes internationaux, fonds de dotation et subventions à recevoir', '45'],
            ['4581', 'Organismes internationaux, fonds de dotation à recevoir', '458'],
            ['4582', 'Organismes internationaux, subventions à recevoir', '458'],
            ['46', 'Apporteurs, associés et groupe', '4'],
            ['461', 'Apporteurs, opérations sur le capital', '46'],
            ['4611', 'Apporteurs apports en nature', '461'],
            ['4612', 'Apporteurs apports en numéraire', '461'],
            ['4613', 'Apporteurs, capital souscrit appelé non versé', '461'],
            ['4614', 'Apporteurs, compte d\'apport, opérations de restructuration (fusion …)', '461'],
            ['4615', 'Apporteurs, versements reçus sur augmentation de capital', '461'],
            ['4616', 'Apporteurs, versements anticipés', '461'],
            ['4617', 'Apporteurs défaillants', '461'],
            ['4618', 'Apporteurs, titres à échanger', '461'],
            ['4619', 'Apporteurs, capital à rembourser', '461'],
            ['462', 'Associés, comptes courants', '46'],
            ['4621', 'Principal', '462'],
            ['4626', 'Intérêts courus', '462'],
            ['463', 'Associés, opérations faites en commun et GIE', '46'],
            ['4631', 'Opérations courantes', '463'],
            ['4636', 'Intérêts courus', '463'],
            ['465', 'Associés, dividendes à payer', '46'],
            ['466', 'Groupe, comptes courants', '46'],
            ['467', 'Apporteurs, restant dû sur capital appelé', '46'],
            ['47', 'Débiteurs et créditeurs divers', '4'],
            ['471', 'Débiteurs et créditeurs divers', '47'],
            ['4711', 'Débiteurs divers (ceux qui nous doivent)', '471'],
            ['4712', 'Créditeurs divers (ceux à qui nous devons – nos créanciers)', '471'],
            ['4713', 'Obligataires', '471'],
            ['4715', 'Rémunérations d\'administrateurs', '471'],
            ['4716', 'Compte d\'affacturage', '471'],
            ['4717', 'Débiteurs divers - retenues de garantie', '471'],
            ['4718', 'Apports, compte de fusion et opérations assimilées', '471'],
            ['4719', 'Bons de souscription d\'actions et obligations', '471'],
            ['472', 'Créances et dettes sur titres de placement', '47'],
            ['4721', 'Créances sur cessions de titres de placement', '472'],
            ['4726', 'Versements restant à effectuer sur titres de placement non libérés', '472'],
            ['473', 'Intermédiaires - opérations faites pour le compte de tiers', '47'],
            ['4731', 'Mandants', '473'],
            ['4732', 'Mandataires', '473'],
            ['4733', 'Commettants', '473'],
            ['4734', 'Commissionnaires', '473'],
            ['4739', 'État, Collectivités publiques, fonds global d\'allocation', '473'],
            ['474', 'Compte répartition périodique des charges et des produits', '47'],
            ['4746', 'Compte de répartition périodique des charges', '474'],
            ['4747', 'Compte de répartition périodique des produits', '474'],
            ['475', 'Compte transitoire, ajustement spécial lié à la revision du SYSCOHADA', '47'],
            ['4751', 'Compte actif', '475'],
            ['4752', 'Compte passif', '475'],
            ['476', 'Charges constatées d\'avance', '47'],
            ['477', 'Produits constatés d\'avance', '47'],
            ['478', 'Écarts de conversion - actif', '47'],
            ['4781', 'Diminution des créances d\'exploitation', '478'],
            ['4782', 'Diminution des créances financière', '478'],
            ['4783', 'Augmentation des dettes d\'exploitation', '478'],
            ['4784', 'Augmentation des dettes financières', '478'],
            ['4786', 'Différences d\'évaluation sur instruments de trésorerie', '478'],
            ['4788', 'Différences compensées par couverture de change', '478'],
            ['479', 'Écarts de conversion - passif', '47'],
            ['4791', 'Diminution des créances d\'exploitation', '479'],
            ['4792', 'Diminution des créances financière', '479'],
            ['4793', 'Augmentation des dettes d\'exploitation', '479'],
            ['4794', 'Augmentation des dettes financières', '479'],
            ['4797', 'Différences d\'évaluation sur instruments de trésorerie', '479'],
            ['4798', 'Différences compensées par couverture de change', '479'],
            ['48', 'Créances et dettes hors activités ordinaires (HAO)', '4'],
            ['481', 'Fournisseurs d\'investissements', '48'],
            ['4811', 'Immobilisations incorporelles', '481'],
            ['4812', 'Immobilisations corporelles', '481'],
            ['4813', 'Versements restant à effectuer sur titres de participation et titres immobilisés non libérés', '481'],
            ['4816', 'Réserve de propriété', '481'],
            ['4817', 'Retenue de garantie', '481'],
            ['4818', 'Factures non parvenues', '481'],
            ['482', 'Fournisseurs d\'investissements, effets à payer', '48'],
            ['4821', 'Immobilisations incorporelles', '482'],
            ['4822', 'Immobilisations corporelles', '482'],
            ['484', 'Autres dettes hors activités ordinaires (H.A.O.)', '48'],
            ['485', 'Créances sur cessions d\'immobilisations', '48'],
            ['4851', 'En compte, immobilisations incorporelles', '485'],
            ['4852', 'En compte, immobilisations corporelles', '485'],
            ['4853', 'Effets à recevoir, immobilisations incorporelles', '485'],
            ['4854', 'Effets à recevoir, immobilisations corporelles', '485'],
            ['4855', 'Effets escomptés non échus', '485'],
            ['4857', 'Retenues de garantie', '485'],
            ['4858', 'Factures à établir', '485'],
            ['488', 'Autres créances hors activités ordinaires (H.A.O.)', '48'],
            ['49', 'Dépréciations et provisions pour risques a court terme (tiers)', '4'],
            ['490', 'Dépréciations des comptes fournisseurs', '49'],
            ['491', 'Dépréciations des comptes Apprenants et familles', '49'],
            ['4911', 'Créances litigieuses', '491'],
            ['4912', 'Créances douteuses', '491'],
            ['492', 'Dépréciations des comptes personnel', '49'],
            ['493', 'Dépréciations des comptes organismes sociaux', '49'],
            ['494', 'Dépréciations des comptes état et collectivités publiques', '49'],
            ['495', 'Dépréciations des comptes organismes internationaux', '49'],
            ['496', 'Dépréciations des comptes apporteurs associés et groupe', '49'],
            ['4962', 'Associés, comptes courants', '496'],
            ['4963', 'Associés, opérations faites en commun', '496'],
            ['4966', 'Groupe, comptes courants', '496'],
            ['497', 'Dépréciations des comptes débiteurs divers', '49'],
            ['498', 'Dépréciations des comptes de créances H.A.O', '49'],
            ['4981', 'Créances sur cessions d\'immobilisations', '498'],
            ['4982', 'Créances sur cessions de titres de placement', '498'],
            ['4988', 'Autres créances H.A.O.', '498'],
            ['499', 'Provisions pour risques a court terme', '49'],
            ['4991', 'Sur opérations d\'exploitation', '499'],
            ['4997', 'Sur opérations financières', '499'],
            ['4998', 'Sur opérations H.A.O.', '499'],
            ['5', 'Comptes de trésorerie', null],
            ['50', 'Titres de placement', '5'],
            ['501', 'Titres du trésor et bons de caisse à court terme', '50'],
            ['5011', 'Titres du Trésor à court terme', '501'],
            ['5012', 'Titres d\'organismes financiers', '501'],
            ['5013', 'Bons de caisse à court terme', '501'],
            ['5016', 'Frais d\'acquisition des titres de trésor et bons de caisse', '501'],
            ['502', 'Actions', '50'],
            ['5021', 'Actions ou parts propres', '502'],
            ['5022', 'Actions cotées', '502'],
            ['5023', 'Actions non cotées', '502'],
            ['5024', 'Actions démembrées (certificats d\'investissement ; droits de vote)', '502'],
            ['5025', 'Autres actions', '502'],
            ['5026', 'Frais d\'acquisition des actions', '502'],
            ['503', 'Obligations', '50'],
            ['5031', 'Obligations émises par la société et rachetées par elle', '503'],
            ['5032', 'Obligations cotées', '503'],
            ['5033', 'Obligations non cotées', '503'],
            ['5035', 'Autres obligations', '503'],
            ['5036', 'Frais d\'acquisition des obligations', '503'],
            ['504', 'Bons de souscription', '50'],
            ['5042', 'Bons de souscription d\'actions', '504'],
            ['5043', 'Bons de souscription d\'obligations', '504'],
            ['505', 'Titres négociables hors région', '50'],
            ['506', 'Intérêts courus', '50'],
            ['5061', 'Titres du Trésor et bons de caisse à court terme', '506'],
            ['5062', 'Actions', '506'],
            ['5063', 'Obligations', '506'],
            ['508', 'Autres titres de placement et créances assimilées', '50'],
            ['51', 'Valeurs à encaisser', '5'],
            ['511', 'Effets à encaisser', '51'],
            ['512', 'Effets à l\'encaissement', '51'],
            ['513', 'Chèques à encaisser', '51'],
            ['514', 'Chèques à l\'encaissement', '51'],
            ['515', 'Cartes de crédit à encaisser', '51'],
            ['518', 'Autres valeurs à l\'encaissement', '51'],
            ['5181', 'Warrants', '518'],
            ['5182', 'Billets de fonds', '518'],
            ['5185', 'Chèques de voyage', '518'],
            ['5186', 'Coupons échus', '518'],
            ['5187', 'Intérêts échus des obligations', '518'],
            ['52', 'Banques', '5'],
            ['521', 'Banques locales', '52'],
            ['5211', 'Banques en monnaie nationale', '521'],
            ['5215', 'Banques en devises', '521'],
            ['522', 'Banques autres Etats région', '52'],
            ['523', 'Banques autres Etats zone monétaire', '52'],
            ['524', 'Banques hors zone monétaire', '52'],
            ['525', 'Banques dépôts à terme', '52'],
            ['526', 'Banques, intérêts courus', '52'],
            ['5261', 'Banques, intérêts courus charges à payer', '526'],
            ['5267', 'Banques, intérêts courus produits à recevoir', '526'],
            ['53', 'Établissements financiers et assimilés', '5'],
            ['531', 'Chèques postaux', '53'],
            ['532', 'Trésor', '53'],
            ['533', 'Sociétés de gestion et d\'intermédiation (S.G.I)', '53'],
            ['536', 'Etablissements financiers, intérêts courus', '53'],
            ['538', 'Autres organismes financiers', '53'],
            ['54', 'Instruments de trésorerie', '5'],
            ['541', 'Options de taux d\'intérêt', '54'],
            ['542', 'Options de taux de change', '54'],
            ['543', 'Options de taux boursiers', '54'],
            ['544', 'Instruments de marchés à terme', '54'],
            ['545', 'Avoirs d\'or et autres métaux précieux', '54'],
            ['55', 'Instruments de monnaie électronique', '5'],
            ['551', 'Monnaie électronique - carte carburant', '55'],
            ['552', 'Monnaie électronique - téléphone portable', '55'],
            ['553', 'Monnaie électronique - carte péage', '55'],
            ['554', 'Porte-monnaie électronique', '55'],
            ['558', 'Autres instruments monnaie électronique', '55'],
            ['56', 'Banques, crédits de trésorerie et d\'escompte', '5'],
            ['561', 'Crédits de trésorerie', '56'],
            ['564', 'Escompte de crédits de campagne', '56'],
            ['565', 'Escompte de crédits ordinaires', '56'],
            ['566', 'Banques, crédits de trésorerie, intérêts courus', '56'],
            ['57', 'Caisse', '5'],
            ['571', 'Caisse siège social', '57'],
            ['5711', 'Caisse en monnaie nationale', '571'],
            ['5712', 'Caisse en devises', '571'],
            ['572', 'Caisse succursale A', '57'],
            ['5721', 'en monnaie nationale', '572'],
            ['5722', 'en devises', '572'],
            ['573', 'Caisse succursale B', '57'],
            ['5731', 'en monnaie nationale', '573'],
            ['5732', 'en devises', '573'],
            ['58', 'Régies d\'avances, accréditifs et virements internes', '5'],
            ['581', 'Régies d\'avance', '58'],
            ['582', 'Accréditifs', '58'],
            ['585', 'Virements de fonds', '58'],
            ['588', 'Autres virements internes', '58'],
            ['59', 'Dépréciations et provisions pour risques a court terme', '5'],
            ['590', 'Dépréciations des titres de placement', '59'],
            ['591', 'Dépréciations des titres et valeurs à encaisser', '59'],
            ['592', 'Dépréciations des comptes banques', '59'],
            ['593', 'Dépréciations des comptes établissements financiers et assimilés', '59'],
            ['594', 'Dépréciations des comptes d’instruments de trésorerie', '59'],
            ['599', 'Dépréciations pour risques à court à caractère financier', '59'],
            ['6', 'Comptes de charges des activités ordinaires', null],
            ['60', 'Achats et variations de stocks', '6'],
            ['601', 'Achats de marchandises', '60'],
            ['6011', 'dans la Région', '601'],
            ['6012', 'hors Région', '601'],
            ['6013', 'aux entités du groupe dans la Région', '601'],
            ['6014', 'aux entités du groupe hors Région', '601'],
            ['6015', 'Frais sur achats', '601'],
            ['6019', 'Rabais, Remises et Ristournes obtenus (non ventilés)', '601'],
            ['602', 'Achats de matières premières et fournitures liées', '60'],
            ['6021', 'dans la Région', '602'],
            ['6022', 'hors Région', '602'],
            ['6023', 'aux entités du groupe dans la Région', '602'],
            ['6024', 'aux entités du groupe hors Région', '602'],
            ['6025', 'Frais sur achats', '602'],
            ['6029', 'Rabais, Remises et Ristournes obtenus (non ventilés)', '602'],
            ['603', 'Variations des stocks de biens achetés', '60'],
            ['6031', 'Variations des stocks de marchandises', '603'],
            ['6032', 'Variations des stocks de matières premières et fournitures liées', '603'],
            ['6033', 'Variations des stocks d\'autres approvisionnements', '603'],
            ['604', 'Achats stockés de matières et fournitures consommables', '60'],
            ['6041', 'Matières consommables', '604'],
            ['6042', 'Matières combustibles', '604'],
            ['6043', 'Produits d\'entretien', '604'],
            ['6044', 'Fournitures d\'atelier et d\'usine', '604'],
            ['6045', 'Frais sur achats', '604'],
            ['6046', 'Fournitures de magasin', '604'],
            ['6047', 'Fournitures de bureau', '604'],
            ['6049', 'Rabais, Remises et Ristournes obtenus (non ventilés)', '604'],
            ['605', 'Autres achats', '60'],
            ['6051', 'Fournitures non stockables - Eau', '605'],
            ['6052', 'Fournitures non stockables - Electricité', '605'],
            ['6053', 'Fournitures non stockables - Autres énergies (Gaz, oxygène, acétylène, etc.)', '605'],
            ['6054', 'Fournitures d\'entretien non stockables', '605'],
            ['6055', 'Fournitures de bureau non stockables', '605'],
            ['6056', 'Achats de petit matériel et outillage', '605'],
            ['6057', 'Achats d\'études et prestations de services', '605'],
            ['6058', 'Achats de travaux, matériels et équipements', '605'],
            ['6059', 'Rabais, Remises et Ristournes obtenus (non ventilés)', '605'],
            ['608', 'Achats d\'emballages', '60'],
            ['6081', 'Emballages perdus', '608'],
            ['6082', 'Emballages récupérables non identifiables', '608'],
            ['6083', 'Emballages à usage mixte', '608'],
            ['6085', 'Frais sur achats', '608'],
            ['6089', 'Rabais, Remises et Ristournes obtenus (non ventilés)', '608'],
            ['61', 'Transports', '6'],
            ['612', 'Transports sur ventes', '61'],
            ['613', 'Transports pour le compte de tiers', '61'],
            ['614', 'Transports du personnel', '61'],
            ['616', 'Transports de plis', '61'],
            ['618', 'Autres frais de transport', '61'],
            ['6181', 'Voyages et déplacements', '618'],
            ['6182', 'Transports entre établissements ou chantiers', '618'],
            ['6183', 'Transports administratifs', '618'],
            ['62', 'Services extérieurs', '6'],
            ['621', 'Sous-traitance générale', '62'],
            ['622', 'Locations, charges locatives', '62'],
            ['6221', 'Locations de terrains', '622'],
            ['6222', 'Locations de bâtiments', '622'],
            ['6223', 'Locations de matériels et outillages', '622'],
            ['6224', 'Malis sur emballages', '622'],
            ['6225', 'Locations d\'emballages', '622'],
            ['6226', 'Fermages et loyers du foncier', '622'],
            ['6228', 'Locations et charges locatives diverses', '622'],
            ['623', 'Redevances de location acquisition', '62'],
            ['6232', 'Crédit-bail immobilier', '623'],
            ['6233', 'Crédit-bail mobilier', '623'],
            ['6234', 'Location-vente', '623'],
            ['6238', 'Autres contrats de location acquisition', '623'],
            ['624', 'Entretien, réparations, remise en état et maintenance', '62'],
            ['6241', 'Entretien et réparations des biens immobiliers', '624'],
            ['6242', 'Entretien et réparations des biens mobiliers', '624'],
            ['6243', 'Maintenance', '624'],
            ['6244', 'Charges de démantèlement et remise en état', '624'],
            ['6248', 'Autres entretiens et réparations', '624'],
            ['625', 'Primes d\'assurance', '62'],
            ['6251', 'Assurances multirisques', '625'],
            ['6252', 'Assurances matériel de transport', '625'],
            ['6253', 'Assurances risques d\'exploitation', '625'],
            ['6254', 'Assurances responsabilité du producteur', '625'],
            ['6255', 'Assurances insolvabilité Apprenants et familles', '625'],
            ['6257', 'Assurances transport sur ventes', '625'],
            ['6258', 'Autres primes d\'assurances', '625'],
            ['626', 'Études, recherches et documentation', '62'],
            ['6261', 'Études et recherches', '626'],
            ['6265', 'Documentation générale', '626'],
            ['6266', 'Documentation technique', '626'],
            ['627', 'Publicité, publications, relations publiques', '62'],
            ['6271', 'Annonces, insertions', '627'],
            ['6272', 'Catalogues, imprimés publicitaires', '627'],
            ['6273', 'Échantillons (cadeaux fabriqués par nous-mêmes)', '627'],
            ['6274', 'Foires et expositions', '627'],
            ['6275', 'Publications', '627'],
            ['6276', 'Cadeaux à la clientèle (cadeaux achetés pour offrir aux Apprenants et familles)', '627'],
            ['6277', 'Frais de colloques, séminaires, conférences', '627'],
            ['6278', 'Autres charges de publicité et relations publiques', '627'],
            ['628', 'Frais de télécommunications', '62'],
            ['6281', 'Frais de téléphone', '628'],
            ['6282', 'Frais de télex', '628'],
            ['6283', 'Frais de télécopie', '628'],
            ['6288', 'Autres frais de télécommunications', '628'],
            ['63', 'Autres services extérieurs', '6'],
            ['631', 'Frais bancaires', '63'],
            ['6311', 'Frais sur titres (vente, garde)', '631'],
            ['6312', 'Frais sur effets', '631'],
            ['6313', 'Location de coffres', '631'],
            ['6314', 'Commission d\'affacturage', '631'],
            ['6315', 'Commissions sur cartes de crédit', '631'],
            ['6316', 'Frais d\'émission d\'emprunts', '631'],
            ['6317', 'Frais sur instruments monnaie électronique', '631'],
            ['6318', 'Autres frais bancaires', '631'],
            ['632', 'Rémunérations d\'intermédiaires et de conseils', '63'],
            ['6322', 'Commissions et courtages sur ventes', '632'],
            ['6324', 'Honoraires des professions règlementées', '632'],
            ['6325', 'Frais d\'actes et de contentieux', '632'],
            ['6326', 'Rémunérations d\'affacturage', '632'],
            ['6327', 'Rémunérations des autres prestataires de services', '632'],
            ['6328', 'Divers frais', '632'],
            ['633', 'Frais de formation du personnel', '63'],
            ['634', 'Redevances pour brevets, licences, logiciels, concessions et droits et valeurs similaires', '63'],
            ['6342', 'Redevances pour brevets, licences, concessions et droits similaires', '634'],
            ['6343', 'Redevances pour logiciels', '634'],
            ['6344', 'Redevances pour marques', '634'],
            ['6345', 'Redevances pour sites internet', '634'],
            ['6346', 'Redevances pour concessions et droits et valeurs similaires', '634'],
            ['635', 'Cotisations', '63'],
            ['6351', 'Cotisations', '635'],
            ['6352', 'Concours divers', '635'],
            ['637', 'Rémunérations de personnel extérieur à l\'entité', '63'],
            ['6371', 'Personnel intérimaire', '637'],
            ['6372', 'Personnel détaché ou prêté à l\'entité', '637'],
            ['638', 'Autres charges externes', '63'],
            ['6381', 'Frais de recrutement du personnel', '638'],
            ['6382', 'Frais de déménagement', '638'],
            ['6383', 'Réceptions', '638'],
            ['6384', 'Missions', '638'],
            ['6385', 'Charges de copropriété', '638'],
            ['64', 'Impôts et taxes', '6'],
            ['641', 'Impôts et taxes directs', '64'],
            ['6411', 'Impôts fonciers et taxes annexes', '641'],
            ['6412', 'Patentes, licences et taxes annexes', '641'],
            ['6413', 'Taxes sur appointements et salaires', '641'],
            ['6414', 'Taxes d\'apprentissage', '641'],
            ['6415', 'Formation professionnelle continue', '641'],
            ['6418', 'Autres impôts et taxes directs', '641'],
            ['645', 'Impôts et taxes indirects', '64'],
            ['646', 'Droits d\'enregistrement', '64'],
            ['6461', 'Droits de mutation', '646'],
            ['6462', 'Droits de timbre', '646'],
            ['6463', 'Taxes sur les véhicules de société', '646'],
            ['6464', 'Vignettes', '646'],
            ['6468', 'Autres droits', '646'],
            ['647', 'Pénalités et amendes fiscales', '64'],
            ['6471', 'Pénalités d\'assiette, impôts directs', '647'],
            ['6472', 'Pénalités d\'assiette, impôts indirects', '647'],
            ['6473', 'Pénalités de recouvrement, impôts directs', '647'],
            ['6474', 'Pénalités de recouvrement, impôts indirects', '647'],
            ['6478', 'Autres pénalités amendes et fiscales', '647'],
            ['648', 'Autres impôts et taxes', '64'],
            ['65', 'Autres charges', '6'],
            ['651', 'Pertes sur créances Apprenants et familles et autres débiteurs', '65'],
            ['6511', 'Apprenants et familles', '651'],
            ['6515', 'Autres débiteurs', '651'],
            ['652', 'Quote-part de résultat sur opérations faites en commun', '65'],
            ['6521', 'Quote-part transférée de bénéfices (comptabilité du gérant)', '652'],
            ['6525', 'Pertes imputées par transfert (comptabilité des associés non gérants)', '652'],
            ['654', 'Valeur comptable des cessions courantes d\'immobilisations', '65'],
            ['6541', 'Immobilisations incorporelles', '654'],
            ['6542', 'Immobilisations corporelles', '654'],
            ['656', 'Perte de change sur créances et dettes commerciales', '65'],
            ['657', 'Pénalités et amendes pénales', '65'],
            ['658', 'Charges diverses', '65'],
            ['6581', 'Indemnités de fonction et autres rémunérations d\'administrateurs', '658'],
            ['6582', 'Dons', '658'],
            ['6583', 'Mécénat', '658'],
            ['6588', 'Autres charges diverses', '658'],
            ['659', 'Charges pour dépréciations et provisions pour risques à court d\'exploitation', '65'],
            ['6591', 'sur risques à court terme', '659'],
            ['6593', 'sur stocks', '659'],
            ['6594', 'sur créances', '659'],
            ['6598', 'Autres charges pour dépréciations et provisions pour risques à court terme', '659'],
            ['66', 'Charges de personnel', '6'],
            ['661', 'Rémunérations directes versées au personnel national', '66'],
            ['6612', 'Primes et gratifications', '661'],
            ['6613', 'Congés payés', '661'],
            ['6614', 'Indemnités de préavis, de licenciement et de recherche d\'embauche', '661'],
            ['6615', 'Indemnités de maladie versées aux travailleurs', '661'],
            ['6616', 'Supplément familial', '661'],
            ['6617', 'Avantages en nature', '661'],
            ['6618', 'Autres rémunérations directes', '661'],
            ['662', 'Rémunérations directes versées au personnel non national', '66'],
            ['6621', 'Appointements salaires et commissions', '662'],
            ['6622', 'Primes et gratifications', '662'],
            ['6623', 'Congés payés', '662'],
            ['6624', 'Indemnités de préavis, de licenciement et de recherche d\'embauche', '662'],
            ['6625', 'Indemnités de maladie versées aux travailleurs', '662'],
            ['6626', 'Supplément familial', '662'],
            ['6627', 'Avantages en nature', '662'],
            ['6628', 'Autres rémunérations directes', '662'],
            ['663', 'Indemnités forfaitaires versées au personnel', '66'],
            ['6631', 'Indemnités de logement', '663'],
            ['6632', 'Indemnités de représentation', '663'],
            ['6633', 'Indemnités d\'expatriation', '663'],
            ['6634', 'Indemnités de transport', '663'],
            ['6638', 'Autres indemnités et avantages divers', '663'],
            ['664', 'Charges sociales', '66'],
            ['6641', 'Charges sociales sur rémunération du personnel national', '664'],
            ['6642', 'Charges sociales sur rémunération du personnel non national', '664'],
            ['666', 'Rémunérations et charges sociales de l\'exploitant individuel', '66'],
            ['6661', 'Rémunération du travail de l\'exploitant', '666'],
            ['6662', 'Charges sociales', '666'],
            ['667', 'Rémunération transférée de personnel extérieur', '66'],
            ['6671', 'Personnel intérimaire', '667'],
            ['6672', 'Personnel détaché ou prêté à l’entité', '667'],
            ['668', 'Autres charges sociales', '66'],
            ['6681', 'Versements aux Syndicats et Comités d\'entreprise, d\'établissement', '668'],
            ['6682', 'Versements aux Comités d\'hygiène et de sécurité', '668'],
            ['6683', 'Versements et contributions aux autres œuvres sociales', '668'],
            ['6684', 'Médecine du travail et pharmacie', '668'],
            ['6685', 'Assurances et organismes de santé', '668'],
            ['6686', 'Assurances retraite et fonds de pension', '668'],
            ['6687', 'Majorations et pénalités sociales', '668'],
            ['6688', 'Charges sociales diverses', '668'],
            ['67', 'Frais financiers et charges assimilées', '6'],
            ['671', 'Intérêts des emprunts', '67'],
            ['6711', 'Emprunts obligataires', '671'],
            ['6712', 'Emprunts auprès des établissements de crédit', '671'],
            ['6713', 'Intérêts sur dettes liées à des participations', '671'],
            ['6714', 'Primes de remboursement des obligations', '671'],
            ['672', 'Intérêts dans loyers de location acquisition', '67'],
            ['6722', 'Intérêts dans loyers de location acquisition/crédit-bail immobilier', '672'],
            ['6723', 'Intérêts dans loyers de location acquisition/crédit-bail mobilier', '672'],
            ['6724', 'Intérêts dans loyers de location acquisition/location-vente', '672'],
            ['6728', 'Intérêts dans loyers des autres locations acquisition', '672'],
            ['673', 'Escomptes accordés', '67'],
            ['674', 'Autres intérêts', '67'],
            ['6741', 'Avances reçues et dépôts créditeurs', '674'],
            ['6742', 'Comptes courants bloqués', '674'],
            ['6743', 'Intérêts sur obligations cautionnées', '674'],
            ['6744', 'Intérêts sur dettes commerciales', '674'],
            ['6745', 'Intérêts bancaires et sur opérations de financement (escompte …)', '674'],
            ['6748', 'Intérêts sur dettes diverses', '674'],
            ['675', 'Escomptes des effets de commerce', '67'],
            ['676', 'Pertes de change financières', '67'],
            ['677', 'Pertes sur cessions de titres de placement', '67'],
            ['6771', 'Pertes sur cessions de titres de placement', '677'],
            ['6772', 'Malis provenant d\'attribution gratuite d\'actions au personnel salarié et aux dirigeants', '677'],
            ['678', 'Pertes et charges sur risques financiers', '67'],
            ['6781', 'sur rentes viagères', '678'],
            ['6782', 'sur opérations financières', '678'],
            ['6784', 'sur instruments de trésorerie', '678'],
            ['679', 'Charges pour dépréciations et provisions pour risques financières a court terme', '67'],
            ['6791', 'sur risques financiers', '679'],
            ['6795', 'sur titres de placement', '679'],
            ['6798', 'Autres charges pour dépréciations et provisions pour risques à court terme financières', '679'],
            ['68', 'Dotations aux amortissements', '6'],
            ['681', 'Dotations aux amortissements d\'exploitation', '68'],
            ['6812', 'Dotations aux amortissements des immobilisations incorporelles', '681'],
            ['6813', 'Dotations aux amortissements des immobilisations corporelles', '681'],
            ['69', 'Dotations aux provisions et aux dépréciations', '6'],
            ['691', 'Dotations aux provisions et aux dépréciations d\'exploitation', '69'],
            ['6911', 'Dotations aux provisions pour risques et charges', '691'],
            ['6913', 'Dotations aux dépréciations des immobilisations incorporelles', '691'],
            ['6914', 'Dotations aux dépréciations des immobilisations corporelles', '691'],
            ['697', 'Dotations aux provisions et aux dépréciations financières', '69'],
            ['6971', 'Dotations aux provisions pour risques et charges', '697'],
            ['6972', 'Dotations aux dépréciations des immobilisations financières', '697'],
            ['7', 'Comptes de produits des activités ordinaires', null],
            ['70', 'Ventes', '7'],
            ['701', 'Ventes de marchandises', '70'],
            ['7011', 'dans la Région', '701'],
            ['7012', 'hors Région', '701'],
            ['7013', 'aux entités du groupe dans la Région', '701'],
            ['7014', 'aux entités du groupe hors Région', '701'],
            ['7015', 'sur internet', '701'],
            ['7019', 'Rabais, Remises et Ristournes accordés (non ventilés)', '701'],
            ['702', 'Ventes de produits finis', '70'],
            ['7021', 'dans la Région', '702'],
            ['7022', 'hors Région', '702'],
            ['7023', 'aux entités du groupe dans la Région', '702'],
            ['7024', 'aux entités du groupe hors Région', '702'],
            ['7025', 'sur internet', '702'],
            ['7029', 'Rabais, Remises et Ristournes accordés (non ventilés)', '702'],
            ['703', 'Ventes de produits intermédiaires', '70'],
            ['7031', 'dans la Région', '703'],
            ['7032', 'hors Région', '703'],
            ['7033', 'aux entités du groupe dans la Région', '703'],
            ['7034', 'aux entités du groupe hors Région', '703'],
            ['7035', 'sur internet', '703'],
            ['7039', 'Rabais, Remises et Ristournes accordés (non ventilés)', '703'],
            ['704', 'Ventes de produits résiduels', '70'],
            ['7041', 'dans la Région', '704'],
            ['7042', 'hors Région', '704'],
            ['7043', 'aux entités du groupe dans la Région', '704'],
            ['7044', 'aux entités du groupe hors Région', '704'],
            ['7045', 'sur internet', '704'],
            ['7049', 'Rabais, Remises et Ristournes accordés (non ventilés)', '704'],
            ['705', 'Travaux facturés', '70'],
            ['7051', 'dans la Région', '705'],
            ['7052', 'hors Région', '705'],
            ['7053', 'aux entités du groupe dans la Région', '705'],
            ['7054', 'aux entités du groupe hors Région', '705'],
            ['7055', 'sur internet', '705'],
            ['7059', 'Rabais, Remises et Ristournes accordés (non ventilés)', '705'],
            ['706', 'Services vendus', '70'],
            ['7061', 'dans la Région', '706'],
            ['7062', 'hors Région', '706'],
            ['7063', 'aux entités du groupe dans la Région', '706'],
            ['7064', 'aux entités du groupe hors Région', '706'],
            ['7065', 'sur internet', '706'],
            ['7069', 'Rabais, Remises et Ristournes accordés (non ventilés)', '706'],
            ['707', 'Produits accessoires', '70'],
            ['7071', 'Ports, emballages perdus et autres frais facturés', '707'],
            ['7072', 'Commissions et courtages', '707'],
            ['7073', 'Locations', '707'],
            ['7074', 'Bonis sur reprises et cessions d\'emballages', '707'],
            ['7075', 'Mise à disposition de personnel', '707'],
            ['7076', 'Redevances pour brevets, logiciels, marques et droits similaires', '707'],
            ['7077', 'Services exploités dans l\'intérêt du personnel', '707'],
            ['7078', 'Autres produits accessoires', '707'],
            ['71', 'Subventions d\'exploitation', '7'],
            ['711', 'sur produits à l\'exportation', '71'],
            ['712', 'sur produits à l\'importation', '71'],
            ['713', 'sur produits de péréquation', '71'],
            ['714', 'Indemnités et subventions d\'exploitation (entité agricole)', '71'],
            ['718', 'Autres subventions d\'exploitation', '71'],
            ['7181', 'Versées par l\'État et les collectivités publiques', '718'],
            ['7182', 'Versées par les organismes internationaux', '718'],
            ['7183', 'Versées par des tiers', '718'],
            ['72', 'Production immobilisée', '7'],
            ['721', 'Immobilisations incorporelles', '72'],
            ['722', 'Immobilisations corporelles', '72'],
            ['7221', 'Immobilisations corporelles (hors actifs biologiques)', '722'],
            ['7222', 'Immobilisations corporelles (actifs biologiques)', '722'],
            ['724', 'Production auto-consommée', '72'],
            ['726', 'Immobilisations financières', '72'],
            ['73', 'Variations des stocks de biens et de services produits', '7'],
            ['734', 'Variations des stocks de produits en cours', '73'],
            ['7341', 'Produits en cours', '734'],
            ['7342', 'Travaux en cours', '734'],
            ['735', 'Variations des en-cours de services', '73'],
            ['7351', 'Études en cours', '735'],
            ['7352', 'Prestations de services en cours', '735'],
            ['736', 'Variations des stocks de produits finis', '73'],
            ['737', 'Variations des stocks de produits intermédiaires et résiduels', '73'],
            ['7371', 'Produits intermédiaires', '737'],
            ['7372', 'Produits résiduels', '737'],
            ['75', 'Autres produits', '7'],
            ['751', 'Profits sur créances Apprenants et familles et autres débiteurs', '75'],
            ['752', 'Quote-part de résultat sur opérations faites en commun', '75'],
            ['7521', 'Quote-part transférée de pertes (comptabilité du gérant)', '752'],
            ['7525', 'Bénéfices attribués par transfert (comptabilité des associés non gérants)', '752'],
            ['754', 'Produits des cessions courantes d\'immobilisations', '75'],
            ['7541', 'Immobilisations incorporelles', '754'],
            ['7542', 'Immobilisations corporelles', '754'],
            ['756', 'Gains de change sur créances et dettes commerciales', '75'],
            ['758', 'Produits divers', '75'],
            ['7581', 'Indemnités de fonction et autres rémunérations d\'administrateurs', '758'],
            ['7582', 'Indemnités d’assurances reçues', '758'],
            ['7588', 'Autres produits divers', '758'],
            ['759', 'Reprises de charges pour dépréciations et provisions pour risques a court terme d\'exploitation', '75'],
            ['7591', 'sur risques à court terme', '759'],
            ['7593', 'sur stocks', '759'],
            ['7594', 'sur créances', '759'],
            ['7598', 'sur autres charges pour dépréciations et provisions pour risques à court terme d\'exploitation', '759'],
            ['77', 'Revenus financiers et produits assimilés', '7'],
            ['771', 'Intérêts de prêts et créances diverses', '77'],
            ['7712', 'Intérêts des prêts', '771'],
            ['7713', 'Intérêts sur créances diverses', '771'],
            ['772', 'Revenus de participations et autres titres immobilises', '77'],
            ['7721', 'Revenus des titres de participation', '772'],
            ['7722', 'Revenus autres titres immobilisés', '772'],
            ['773', 'Escomptes obtenus', '77'],
            ['774', 'Revenus de placement', '77'],
            ['7745', 'Revenus des obligations', '774'],
            ['7746', 'Revenus des titres de placement', '774'],
            ['775', 'Intérêts dans loyers de location acquisition', '77'],
            ['776', 'Gains de change financiers', '77'],
            ['777', 'Gains sur cessions de titres de placement', '77'],
            ['778', 'Gains sur risques financiers', '77'],
            ['7781', 'sur rentes viagères', '778'],
            ['7782', 'sur opérations financières', '778'],
            ['7784', 'sur instruments de trésorerie', '778'],
            ['779', 'Reprises de charges pour dépréciations et provisions a court terme financières', '77'],
            ['7791', 'sur risques financiers', '779'],
            ['7795', 'sur titres de placement', '779'],
            ['7798', 'sur autres charges pour dépréciations et provisions pour risques à court terme financières', '779'],
            ['78', 'Transferts de charges', '7'],
            ['781', 'Transferts de charges d\'exploitation', '78'],
            ['787', 'Transferts de charges financières', '78'],
            ['79', 'Reprises de provisions, de dépréciations et autres', '7'],
            ['791', 'Reprises de provisions et dépréciations d\'exploitation', '79'],
            ['7911', 'pour risques et charges', '791'],
            ['7913', 'des immobilisations incorporelles', '791'],
            ['7914', 'des immobilisations corporelles', '791'],
            ['797', 'Reprises de provisions et dépréciations financières', '79'],
            ['7971', 'pour risques et charges', '797'],
            ['7972', 'des immobilisations financières', '797'],
            ['798', 'Reprises d\'amortissements', '79'],
            ['799', 'Reprises de subventions d’investissement', '79'],
            ['8', 'Comptes des autres charges et des autres produits', null],
            ['81', 'Valeurs comptables des cessions d\'immobilisations', '8'],
            ['811', 'Immobilisations incorporelles', '81'],
            ['812', 'Immobilisations corporelles', '81'],
            ['816', 'Immobilisations financières', '81'],
            ['82', 'Produits des cessions d\'immobilisations', '8'],
            ['821', 'Immobilisations incorporelles', '82'],
            ['822', 'Immobilisations corporelles', '82'],
            ['826', 'Immobilisations financières', '82'],
            ['83', 'Charges hors activités ordinaires', '8'],
            ['831', 'Charges H.A.O constatées', '83'],
            ['834', 'Pertes sur créances H.A.O', '83'],
            ['835', 'Dons et libéralités accordés', '83'],
            ['836', 'Abandons de créances consentis', '83'],
            ['837', 'Charges liées aux opérations de liquidation', '83'],
            ['839', 'Charges pour dépréciations et provisions pour risques a court terme H.A.O', '83'],
            ['84', 'Produits hors activités ordinaires', '8'],
            ['841', 'Produits H.A.O constatés', '84'],
            ['843', 'Produits lies aux opérations de restructuration', '84'],
            ['844', 'Indemnités et subventions H.A.O (entité agricole)', '84'],
            ['845', 'Dons et libéralités obtenus', '84'],
            ['846', 'Abandons de créances obtenus', '84'],
            ['847', 'Produits lies aux opérations de liquidation', '84'],
            ['848', 'Transferts de charges H.A.O', '84'],
            ['849', 'Reprises des charges pour dépréciations et provisions pour risques et charges H.A.O.', '84'],
            ['85', 'Dotations hors activités ordinaires', '8'],
            ['851', 'Dotations aux provisions réglementées', '85'],
            ['852', 'Dotations aux amortissements H.A.O', '85'],
            ['853', 'Dotations aux dépréciations H.A.O', '85'],
            ['854', 'Dotations aux provisions pour risques et charges H.A.O', '85'],
            ['858', 'Autres dotations H.A.O.', '85'],
            ['86', 'Reprises hors activités ordinaires', '8'],
            ['861', 'Reprises de provisions réglementées', '86'],
            ['862', 'Reprises d’amortissements H.A.O', '86'],
            ['863', 'Reprises de dépréciation H.A.O', '86'],
            ['864', 'Reprises de provisions pour risques et charges H.A.O', '86'],
            ['868', 'Autres reprises H.A.O.', '86'],
            ['87', 'Participation des travailleurs', '8'],
            ['871', 'Participation légale aux bénéfices', '87'],
            ['874', 'Participation contractuelle aux bénéfices', '87'],
            ['878', 'Autres participations', '87'],
            ['88', 'Subventions d\'équilibre', '8'],
            ['881', 'État', '88'],
            ['884', 'Collectivités publiques', '88'],
            ['886', 'Groupe', '88'],
            ['888', 'Autres', '89'],
            ['89', 'Impôts sur le résultat', '8'],
            ['891', 'Impôts sur les bénéfices de l\'exercice', '89'],
            ['8911', 'Activités exercées dans l\'État', '891'],
            ['8912', 'Activités exercées dans les autres États de la Région', '891'],
            ['8913', 'Activités exercées hors Région', '891'],
            ['892', 'Rappel d\'impôts sur résultats antérieurs', '89'],
            ['895', 'Impôt minimum forfaitaire (I.M.F)', '89'],
            ['899', 'Dégrèvements et annulations d’impôts sur résultats antérieurs', '89'],
            ['8991', 'Dégrèvements', '899'],
            ['8994', 'Annulations pour pertes rétroactives', '899'],
            ['9', 'Comptes des engagements hors bilan et comptes de la comptabilité analytique de gestion', null],
            ['90', 'Engagements obtenus et engagements accordés', '9'],
            ['901', 'Engagements de financement obtenus', '90'],
            ['9011', 'Crédits confirmés obtenus', '901'],
            ['9012', 'Emprunts restant à encaisser', '901'],
            ['9013', 'Facilités de financement renouvelables', '901'],
            ['9014', 'Facilités d\'émission', '901'],
            ['9018', 'Autres engagements de financement obtenus', '901'],
            ['902', 'Engagements de garantie obtenus', '90'],
            ['9021', 'Avals obtenus', '902'],
            ['9022', 'Cautions, garanties obtenues', '902'],
            ['9023', 'Hypothèques obtenues', '902'],
            ['9024', 'Effets endossés par des tiers', '902'],
            ['9028', 'Autres garanties obtenues', '902'],
            ['903', 'Engagements réciproques', '90'],
            ['9031', 'Achats de marchandises à terme', '903'],
            ['9032', 'Achats à terme de devises', '903'],
            ['9033', 'Commandes fermes des Apprenants et familles', '903'],
            ['9038', 'Autres engagements réciproques', '903'],
            ['904', 'Autres engagements obtenus', '90'],
            ['9041', 'Abandons de créances conditionnels', '904'],
            ['9043', 'Ventes avec clause de réserve de propriété', '904'],
            ['9048', 'Divers engagements obtenus', '904'],
            ['905', 'Engagements de financement accordés', '90'],
            ['9051', 'Crédits accordés non décaissés', '905'],
            ['9058', 'Autres engagements de financement accordés', '905'],
            ['906', 'Engagements de garantie accordés', '90'],
            ['9061', 'Avals accordés', '906'],
            ['9062', 'Cautions, garanties accordées', '906'],
            ['9063', 'Hypothèques accordées', '906'],
            ['9064', 'Effets endossés par l\'entreprise', '906'],
            ['9068', 'Autres garanties accordées', '906'],
            ['907', 'Engagements réciproques', '90'],
            ['9071', 'Ventes de marchandises à terme', '907'],
            ['9072', 'Ventes à terme de devises', '907'],
            ['9073', 'Commandes fermes aux fournisseurs', '907'],
            ['9078', 'Autres engagements réciproques', '907'],
            ['908', 'Autres engagements accordés', '90'],
            ['9081', 'Annulations conditionnelles de dettes', '908'],
            ['9082', 'Engagements de retraite', '908'],
            ['9083', 'Achats avec clause de réserve de propriété', '908'],
            ['9088', 'Divers engagements accordés', '908'],
            ['91', 'Contreparties des engagements', '9'],
            ['92', 'Comptes réfléchis', '9'],
            ['93', 'Comptes de reclassements', '9'],
            ['94', 'Comptes de coûts', '9'],
            ['95', 'Comptes de stocks', '9'],
            ['96', 'Comptes d\'écarts sur couts préétablis', '9'],
            ['97', 'Comptes de différences de traitement comptable', '9'],
            ['98', 'Comptes de résultats', '9'],
            ['99', 'Comptes de liaisons internes', '9'],
            ['99', 'Comptes de liaisons internes', '9'],
        ];

        // 1) Insertion des comptes manquants.
        foreach ($comptes as [$num, $lib, $parent]) {
            if (!DB::table('plan_comptes')->where('numero_compte', $num)->exists()) {
                DB::table('plan_comptes')->insert([
                    'numero_compte' => $num,
                    'libelle_compte' => $lib,
                    'etat' => 'actif',
                    'creation_username' => 'system',
                    'created_at' => now(), 'updated_at' => now(),
                ]);
            }
        }

        // 2) Rattachement parent (compte_parent_id) via le numero de compte parent.
        $ids = DB::table('plan_comptes')->pluck('id', 'numero_compte');
        foreach ($comptes as [$num, $lib, $parent]) {
            if ($parent !== null && isset($ids[$num], $ids[$parent])) {
                DB::table('plan_comptes')->where('id', $ids[$num])
                    ->whereNull('compte_parent_id')
                    ->update(['compte_parent_id' => $ids[$parent]]);
            }
        }
    }

    public function down(): void
    {
        // Import de reference : on ne supprime pas au rollback.
    }
};
